const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const projects = require('../projects.js');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');

assert.strictEqual(projects.length, 24, '포트폴리오에는 현재 24개 공개 프로젝트가 있어야 합니다.');
assert.strictEqual(new Set(projects.map(p => p.id)).size, projects.length, '프로젝트 ID는 고유해야 합니다.');
projects.forEach(project => {
  ['id', 'title', 'url', 'image', 'kind', 'summary'].forEach(key => assert(project[key], `${project.id || 'project'}: ${key} 필드가 필요합니다.`));
  assert(/^https:\/\//.test(project.url), `${project.id}: 공개 HTTPS 링크가 필요합니다.`);
  assert(Array.isArray(project.tags) && project.tags.length, `${project.id}: 태그가 필요합니다.`);
  assert(fs.existsSync(path.join(root, project.image)), `${project.id}: 대표 이미지 파일이 실제로 존재해야 합니다.`);
});

const featured = projects.filter(p => p.featured);
assert.deepStrictEqual(featured.map(p => p.id), ['magic-brick', 'make-tteok', 'neon-dash-waves']);
assert(/18,?000|1\.8만/.test(projects.find(p => p.id === 'magic-brick').impact));
assert(/2인|2-person/i.test(projects.find(p => p.id === 'make-tteok').impact));
assert(/1시간|60\s*minute/i.test(projects.find(p => p.id === 'neon-dash-waves').impact));
assert(projects.some(p => p.url === 'https://woo12345678.github.io/lotto-signal-lab/'));
assert(projects.some(p => p.url === 'https://woo12345678.github.io/korea-atmosphere-live/'));
assert(projects.some(p => p.url === 'https://woo12345678.github.io/bluetooth-shower-playground/'));
assert(projects.some(p => p.url === 'https://woo12345678.github.io/cyber-air-conditioner/'));
assert(projects.some(p => p.url === 'https://woo12345678.github.io/click-fireworks/'));
assert(projects.some(p => p.url === 'https://woo12345678.github.io/mosquito-hunt/'));
assert(projects.some(p => p.url === 'https://woo12345678.github.io/character-vault/'));
assert(projects.some(p => p.url === 'https://woo12345678.github.io/infinite-cat-desk/'));
assert(projects.some(p => p.url === 'https://do0rian.itch.io/hotdog-street-empire'));
const lifeHelp = projects.find(p => p.id === 'hannun-life-help');
assert(lifeHelp, '한눈 생활도움 프로젝트가 필요합니다.');
assert.strictEqual(lifeHelp.url, 'https://woo12345678.github.io/hannun-life-help/');
assert.strictEqual(lifeHelp.image, 'assets/projects/hannun-life-help.png');
assert(/광고/.test(lifeHelp.summary + lifeHelp.impact), '광고 문의 수익 모델을 표시해야 합니다.');
assert(/6\/6/.test(lifeHelp.impact), '검증된 테스트 수를 표시해야 합니다.');
const playlog = projects.find(p => p.id === 'playlog');
assert(playlog, 'PLAYLOG 프로젝트가 필요합니다.');
assert.strictEqual(playlog.url, 'https://woo12345678.github.io/playlog/');
assert.strictEqual(playlog.image, 'assets/projects/playlog.png');
assert(/71 Game DB/.test(playlog.impact), 'PLAYLOG의 검증된 게임 지식 DB 규모를 표시해야 합니다.');
assert(/10 Seeds/.test(playlog.impact), 'PLAYLOG의 다중 게임 입력 범위를 표시해야 합니다.');
assert(/Custom Entry/.test(playlog.impact), 'PLAYLOG의 목록에 없는 게임 직접 추가를 표시해야 합니다.');
assert(/17\/17/.test(playlog.impact), 'PLAYLOG의 통과 테스트 수를 표시해야 합니다.');
assert(playlog.tags.includes('Memory Finder'), 'PLAYLOG 추억 게임 찾기를 표시해야 합니다.');
assert(playlog.tags.includes('Custom Game Entry'), 'PLAYLOG 사용자 게임 추가 기능을 표시해야 합니다.');
const ladybugGarden = projects.find(p => p.id === 'ladybug-garden');
assert(ladybugGarden, 'Ladybug Garden 프로젝트가 필요합니다.');
assert.strictEqual(ladybugGarden.url, 'https://woo12345678.github.io/do0rian-portfolio/games/ladybug-garden/1a98be2/');
assert.strictEqual(ladybugGarden.image, 'assets/projects/ladybug-garden.png');
assert(/v1\.1\.2/.test(ladybugGarden.impact), 'Ladybug Garden 최신 공개 버전을 표시해야 합니다.');
assert(/1a98be2/.test(ladybugGarden.impact), 'Ladybug Garden 최신 전체화면 빌드 ID를 표시해야 합니다.');
assert(/FULLSCREEN BUILD/.test(ladybugGarden.platform), 'Ladybug Garden 카드에 전체화면 빌드를 노출해야 합니다.');
assert(/77\/77/.test(ladybugGarden.impact), 'Ladybug Garden 최신 테스트 수를 표시해야 합니다.');
assert(ladybugGarden.tags.includes('Mobile Fullscreen'), 'Ladybug Garden 모바일 전체화면 지원을 표시해야 합니다.');
const embeddedLadybugIndex = fs.readFileSync(path.join(root, 'games/ladybug-garden/1a98be2/index.html'), 'utf8');
assert(embeddedLadybugIndex.includes('index-B2wdraPW.js'), '포트폴리오에는 최신 Ladybug 전체화면 배포 산출물이 포함되어야 합니다.');

['hero', 'selectedWork', 'projectArchive', 'process', 'about'].forEach(id => assert(html.includes(`id="${id}"`), `${id} 섹션이 필요합니다.`));
assert(html.includes('id="ambientCanvas"'), '히어로 앰비언트 캔버스가 필요합니다.');
assert(html.includes('id="projectGrid"'), '확장 가능한 프로젝트 그리드가 필요합니다.');
assert(html.indexOf('projects.js') < html.indexOf('app.js'), '프로젝트 데이터는 앱보다 먼저 로드되어야 합니다.');
assert(css.includes('prefers-reduced-motion'), '모션 감소 접근성을 지원해야 합니다.');
console.log(`PASS: ${projects.length} projects, ${featured.length} featured case studies, extensible portfolio shell`);
