(function(){
'use strict';
const R=window.GulpGoalRules, canvas=document.querySelector('#game'), ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s), ui={title:$('#title'),overlay:$('#overlay'),kicker:$('#overlay-kicker'),overlayTitle:$('#overlay-title'),detail:$('#overlay-detail'),replay:$('#replay'),start:$('#start'),nextShot:$('#next-shot'),formula:$('#shot-formula'),crew:$('#crew'),combo:$('#combo'),wave:$('#wave'),overdrive:$('#overdrive'),overdriveLabel:$('#overdrive-label'),mute:$('#mute'),pause:$('#pause'),announce:$('#announce'),phaseRail:$('#phase-rail'),phaseFeed:$('#phase-feed'),phaseGoal:$('#phase-goal'),progressFill:$('#progress-fill'),progressLabel:$('#progress-label'),launchIntro:$('#launch-intro'),goalCopy:$('#goal-copy'),goalLaunch:$('#goal-launch'),goalCount:$('#goal-count'),aimGuide:$('#aim-guide')};
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let W=0,H=0,DPR=1,last=0,raf=0,audio=null,muted=false,runSerial=0,lastVisual={portalWidth:0,portalHeight:0,tutorial:null};
const colors=['#e94b35','#2862c9','#f6c945','#71c5a6','#f08ab3'];
const normalVolleyColors=['#e94b35','#2862c9','#f6c945'];
let g=makeGame('MAYHEM');
function makeGame(seed){return {state:'title',seed:String(seed),wave:0,phase:'feed',phaseTime:0,launchTime:0,waveTime:0,lane:0,targetLane:0,diameter:16,combo:0,shotBonus:0,score:0,crew:4,volleyMultiplier:1,overdriveCharge:0,overdriveTime:0,overdriveVolleyArmed:false,preparedShotCount:null,preparedShotParticles:0,preparedShotRainbow:false,volleyRainbow:false,speedFactor:1,bumpTime:0,items:[],gates:[],particles:[],stamps:[],balls:[],logicalVolley:0,scored:0,goalNeed:0,goalie:0,gateTaken:{},tallyTime:0,shake:0,best:readBest(),pausedFrom:null,pauseSource:null,tutorial:0,lastCollision:null,lastGate:null,attracted:0,attractionCount:0,lastAnnouncedCombo:0};}
function readBest(){try{return Number(localStorage.getItem('gulp-goal-best')||0)||0}catch(e){return 0}}
function saveBest(v){try{localStorage.setItem('gulp-goal-best',String(v))}catch(e){}}
function resize(){const r=canvas.getBoundingClientRect();DPR=Math.min(2,window.devicePixelRatio||1);W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);}
function announce(text){ui.announce.textContent='';requestAnimationFrame(()=>{ui.announce.textContent=text})}
function start(seed){initAudio();runSerial++;g=makeGame(seed||('GULP-'+Date.now().toString(36).toUpperCase()));g.state='playing';ui.title.hidden=true;ui.phaseRail.hidden=false;ui.overlay.hidden=true;ui.replay.hidden=true;ui.overlay.removeAttribute('role');ui.overlay.removeAttribute('aria-modal');loadWave();announce('대소동 시작. 작은 음식을 먹어 다음 슛을 키우세요.');beep(140,.12,'sawtooth',.05);canvas.focus({preventScroll:true});}
function loadWave(){const l=R.generateWave(g.seed,g.wave);g.items=l.items.map(x=>Object.assign({},x,{alive:true,fall:0}));if(g.wave===0){Object.assign(g.items[0],{x:-.58,y:7,kind:'food',diameter:7});Object.assign(g.items[1],{x:0,y:7,kind:'hazard',diameter:24});Object.assign(g.items[2],{x:.58,y:7,kind:'capsule',diameter:13});}g.gates=l.gates;g.phase='feed';g.phaseTime=0;g.waveTime=0;g.volleyMultiplier=1;g.preparedShotCount=null;g.preparedShotParticles=0;g.preparedShotRainbow=false;g.gateTaken={};g.balls=[];g.tutorial=g.wave===0?8:0;}
function setLane(clientX){const r=canvas.getBoundingClientRect();g.targetLane=Math.max(-1,Math.min(1,((clientX-r.left)/r.width-.5)*2));}
function overdrive(){if(g.state==='playing'&&g.overdriveCharge>=100&&g.overdriveTime<=0){const before=R.previewVolley(g,g.wave);Object.assign(g,R.activateOverdrive(g));const after=R.previewVolley(g,g.wave);g.stamps.push({text:'다음 슛 '+before+' → '+after+'발',life:1.2,color:'#2862c9'});announce('오버드라이브! 다음 슛 '+after.toLocaleString()+'발.');beep(95,.5,'sawtooth',.08);}}
function pause(toggle,source='manual'){if(toggle&&(g.state==='playing'||g.state==='wave-tally')){g.pausedFrom=g.state;g.pauseSource=source;g.state='paused';ui.pause.hidden=false;announce('일시정지. P 또는 Escape 키로 계속하세요.')}else if(!toggle&&g.state==='paused'){g.state=g.pausedFrom||'playing';g.pausedFrom=null;g.pauseSource=null;ui.pause.hidden=true;last=performance.now();announce('게임 계속.')}}
function advanceTally(dt){g.tallyTime=Math.max(0,g.tallyTime-dt);if(g.tallyTime===0){g.wave++;g.diameter=Math.min(48,g.diameter+4);g.crew+=5;ui.overlay.hidden=true;ui.overlay.removeAttribute('role');g.state='playing';loadWave();announce((g.wave+1)+'구역 시작.');}}
function step(dt){dt=Math.min(.05,Math.max(0,dt));if(g.state==='wave-tally'){advanceTally(dt);updateUI();return}if(g.state!=='playing')return;g.phaseTime+=dt;g.overdriveTime=Math.max(0,g.overdriveTime-dt);if(g.bumpTime>0){g.bumpTime-=dt;if(g.bumpTime<=0)g.speedFactor=1}g.lane+=(g.targetLane-g.lane)*Math.min(1,dt*9);if(g.phase==='feed')updateFeed(dt);else if(g.phase==='launch')updateLaunch(dt);else if(g.phase==='goal')updateGoal(dt);updateFX(dt);updateUI();}
function updateFeed(dt){const active=g.overdriveTime>0,speed=(active?1.38:1)*g.speedFactor;g.waveTime+=dt*5.1*speed;g.tutorial=Math.max(0,g.tutorial-dt);g.attracted=0;for(const it of g.items){if(!it.alive)continue;const dy=it.y-g.waveTime;if(active&&it.kind!=='hazard'&&Math.abs(dy)<9){const before=it.x;it.x=R.attractTowardLane(it.x,g.lane,dt,true);if(it.x!==before){g.attracted++;g.attractionCount++;}}if(Math.abs(dy)<2.2&&Math.abs(it.x-g.lane)<R.captureRadius(active)){const action=R.resolveCollision(it.kind,g.diameter,it.diameter,active);g.lastCollision=action;it.alive=false;if(action==='swallow'||action==='recruit'){const before=R.previewVolley(g,g.wave),old=g.diameter;Object.assign(g,R.swallow(g,it.diameter));if(action==='recruit'){const added=3+g.wave;g.crew+=added;const after=R.previewVolley(g,g.wave);stamp('크루 +'+added+' · '+before+' → '+after+'발','blue');announce('크루 '+added+'명 영입. 다음 슛 '+before+'에서 '+after+'발.');}else{const after=R.previewVolley(g,g.wave);stamp('다음 슛 '+before+' → '+after+'발','red');announce('먹기 성공. 다음 슛 '+after+'발.');if(g.combo>=3&&g.combo%3===0&&g.combo!==g.lastAnnouncedCombo)g.lastAnnouncedCombo=g.combo;}burst(it.x,0,7);beep(180+g.combo*22,.045,'square',.025);g.shake=Math.min(5,g.shake+Math.max(0,g.diameter-old));}else{Object.assign(g,R.bump(g));stamp('피하기 실패!','yellow');announce('장애물 충돌. 콤보가 초기화되었습니다.');beep(70,.12,'sawtooth',.045);g.shake=7;}}}
for(let i=0;i<g.gates.length;i++){const gate=g.gates[i];if(!g.gateTaken[i]&&g.waveTime>=gate.y){g.gateTaken[i]=true;const choice=g.lane<0?gate.left:gate.right;g.lastGate=choice;Object.assign(g,R.applyGate(g,choice));const after=R.previewVolley(g,g.wave);stamp('다음 슛 '+after+'발','blue');announce('게이트 선택. 다음 슛 '+after.toLocaleString()+'발.');beep(310,.16,'triangle',.04);}}
if(g.waveTime>=R.WAVE_LENGTH-6)beginLaunch();}
function beginLaunch(){g.waveTime=R.WAVE_LENGTH-6;g.phase='launch';g.phaseTime=0;g.launchTime=.8;const prepared=R.prepareVolley(g,g.wave),v=prepared.volley,palette=v.rainbow?colors:normalVolleyColors;Object.assign(g,prepared.state);g.logicalVolley=g.preparedShotCount;g.volleyRainbow=g.preparedShotRainbow;g.scored=0;g.goalNeed=g.wave===2?Math.ceil(g.preparedShotCount*.48):0;g.balls=Array.from({length:g.preparedShotParticles},(_,i)=>{const column=i%11-5;return{x:column*.075,y:0,t:-i/g.preparedShotParticles,fan:column/5,color:palette[i%palette.length],hit:false}});announce('준비한 '+g.preparedShotCount.toLocaleString()+'발. 지금 전부 슛!');}
function updateLaunch(dt){const next=R.tickClarityPhase({phase:g.phase,launchTime:g.launchTime},dt,false);g.phase=next.phase;g.launchTime=next.launchTime;if(g.phase==='goal')g.phaseTime=0;}
function updateGoal(dt){const duration=g.wave===2?9:5;g.goalie=Math.sin(g.phaseTime*2.4)*.55;let ratio=Math.min(1,g.phaseTime/(duration-.7));if(g.wave<2){const hoopAim=Math.min(1,Math.abs(g.lane)*1.45);g.scored=Math.round(g.logicalVolley*ratio*(.58+.40*hoopAim));}else{const gap=Math.abs(g.lane-g.goalie);const aim=gap>.32?1:.12;g.scored=Math.min(g.logicalVolley,Math.round(g.scored+dt*g.logicalVolley/duration*(.16+aim)));}
for(const b of g.balls){b.t+=dt*(1.4+g.wave*.18);if(b.t>1)b.t-=1.05;}
if(g.phaseTime>=duration){const win=g.wave<2||g.scored>=g.goalNeed;g.score+=g.scored*(g.wave+1);if(g.wave<2)beginTally();else finish(win);}}
function beginTally(){g.state='wave-tally';g.tallyTime=2.45;ui.overlay.hidden=false;ui.overlay.setAttribute('role','status');ui.kicker.textContent=(g.wave+1)+'구역 완료 · DISTRICT CLEAR';ui.overlayTitle.textContent=['꿀꺽 도장!','폭발 도장!'][g.wave];ui.detail.textContent='먹어서 만든 '+g.logicalVolley.toLocaleString()+'발 중 '+g.scored.toLocaleString()+'골 · 크루 '+g.crew+'명';announce((g.wave+1)+'구역 집계. 준비한 '+g.logicalVolley.toLocaleString()+'발 중 '+g.scored.toLocaleString()+'골.');}
function finish(win){g.state=win?'victory':'game-over';g.score+=win?10000:0;if(g.score>g.best){g.best=g.score;saveBest(g.score)}ui.overlay.hidden=false;ui.overlay.setAttribute('role','dialog');ui.overlay.setAttribute('aria-modal','false');ui.overlay.setAttribute('aria-labelledby','overlay-title');ui.replay.hidden=false;ui.kicker.textContent=win?'FINAL GOLDEN GOAL':'골키퍼가 막았다!';ui.overlayTitle.textContent=win?'대소동 승리!':'한 번 더!';ui.detail.innerHTML='먹어서 만든 '+g.logicalVolley.toLocaleString()+'발 중 '+g.scored.toLocaleString()+'골<br>'+(win?'황금 골문 폭발!':'좌우 빈틈을 노려요')+' · 점수 '+g.score.toLocaleString()+'<br>SEED '+escapeHtml(g.seed);announce((win?'대소동 승리! ':'게임 오버. ')+'먹어서 만든 '+g.logicalVolley.toLocaleString()+'발 중 '+g.scored.toLocaleString()+'골.');ui.replay.focus();confetti();}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function updateFX(dt){g.shake=Math.max(0,g.shake-dt*14);for(const p of g.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=90*dt}g.particles=g.particles.filter(p=>p.life>0);for(const s of g.stamps)s.life-=dt;g.stamps=g.stamps.filter(s=>s.life>0)}
function burst(x,y,n){if(reduced)return;for(let i=0;i<n;i++)g.particles.push({x,y,life:.65,vx:(Math.random()-.5)*45,vy:-25-Math.random()*50,color:colors[i%colors.length]})}
function confetti(){if(reduced)return;for(let i=0;i<80;i++)g.particles.push({x:(Math.random()*2-1),y:-1-Math.random(),life:3,vx:(Math.random()-.5)*.5,vy:.3+Math.random(),color:colors[i%5]})}
function stamp(text,color){g.stamps.push({text,life:.75,color:color==='blue'?'#2862c9':color==='yellow'?'#f6c945':'#e94b35'})}
function updateUI(){const goalSide=g.phase==='launch'||g.phase==='goal',next=goalSide&&g.preparedShotCount!==null?g.preparedShotCount:R.previewVolley(g,g.wave),prepared=g.preparedShotCount===null?0:g.preparedShotCount,progress=R.feedProgress(g.waveTime);ui.nextShot.textContent=next.toLocaleString()+'발';ui.formula.textContent='크기 '+Math.round(g.diameter)+' · 크루 '+g.crew+' · 배율 ×'+g.volleyMultiplier;ui.crew.textContent='×'+String(g.crew).padStart(2,'0');ui.combo.textContent='×'+g.combo;ui.wave.textContent=(g.wave+1)+' / 3';ui.phaseFeed.classList.toggle('active',!goalSide);ui.phaseGoal.classList.toggle('active',goalSide);ui.progressFill.style.width=progress+'%';ui.progressLabel.textContent=goalSide?'골대 도착 · 전부 발사!':'골대까지 '+progress+'%';ui.launchIntro.hidden=g.phase!=='launch';ui.launchIntro.textContent='준비한 '+prepared.toLocaleString()+'발 → 지금 전부 슛!';ui.goalCopy.hidden=g.phase!=='goal';ui.goalLaunch.textContent=prepared.toLocaleString()+'발 발사!';ui.goalCount.textContent='골 0 → '+g.scored.toLocaleString();ui.aimGuide.textContent=g.wave===2?'골키퍼 반대쪽 조준':'좌우로 조준해 배수 링 통과';const c=Math.round(g.overdriveTime>0?g.overdriveTime/5*100:g.overdriveCharge);ui.overdrive.style.setProperty('--charge',Math.min(100,c)+'%');ui.overdrive.disabled=g.overdriveCharge<100||g.overdriveTime>0;ui.overdrive.classList.toggle('ready',g.overdriveCharge>=100&&g.overdriveTime<=0);ui.overdrive.classList.toggle('active',g.overdriveTime>0);ui.overdriveLabel.textContent=g.overdriveTime>0?g.overdriveTime.toFixed(1)+'초':Math.round(g.overdriveCharge)+'%';ui.mute.setAttribute('aria-pressed',String(muted));ui.mute.setAttribute('aria-label',muted?'소리 켜기':'소리 끄기');}
function initAudio(){if(audio)return;try{audio=new (window.AudioContext||window.webkitAudioContext)();audio.resume()}catch(e){}}
function beep(freq,dur,type,vol){if(!audio||muted)return;const o=audio.createOscillator(),gain=audio.createGain();o.type=type;o.frequency.value=freq;gain.gain.setValueAtTime(vol,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(gain).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
function loop(t){const dt=(t-last)/1000||0;last=t;step(dt);draw();raf=requestAnimationFrame(loop)}
function draw(){ctx.setTransform(DPR,0,0,DPR,0,0);ctx.clearRect(0,0,W,H);ctx.save();if(g.shake&&!reduced)ctx.translate((Math.random()-.5)*g.shake,(Math.random()-.5)*g.shake);drawWorld();ctx.restore();}
function drawWorld(){ctx.fillStyle='#f3e8ca';ctx.fillRect(0,0,W,H);const laneW=Math.min(W*.72,620),lx=(W-laneW)/2;ctx.fillStyle='#17263b';ctx.fillRect(lx,0,laneW,H);ctx.strokeStyle='#f3e8ca';ctx.lineWidth=3;ctx.setLineDash([14,18]);ctx.beginPath();ctx.moveTo(W/2,0);ctx.lineTo(W/2,H);ctx.stroke();ctx.setLineDash([]);drawBuildings(lx,laneW);if(g.state==='title')return;if(g.phase==='feed')drawFeed(lx,laneW);else drawGoal(lx,laneW);drawCrew(lx,laneW);drawFX(lx,laneW);}
function drawBuildings(lx,lw){for(let side=0;side<2;side++)for(let i=0;i<8;i++){const seed=(i*43+side*97+g.wave*19)%71,h=45+seed%80,w=Math.max(24,(W-lw)/2-12),x=side?lx+lw+6:6,y=(i*121-(g.waveTime*12)%121)-30;ctx.fillStyle=colors[(i+side+g.wave)%4];ctx.fillRect(x,y,w,h);ctx.strokeStyle='#17263b';ctx.lineWidth=3;ctx.strokeRect(x,y,w,h);ctx.fillStyle='#f3e8ca';for(let yy=y+13;yy<y+h-5;yy+=18)ctx.fillRect(x+9,yy,8,8)}}
function xy(lx,lw,x,dy){return {x:lx+lw/2+x*lw*.42,y:H*.65-(dy)*H/24}}
function drawFeed(lx,lw){const annotated={portal:false,food:false,hazard:false,capsule:false,bounds:[]};for(const it of g.items){if(!it.alive)continue;const p=xy(lx,lw,it.x,it.y-g.waveTime);if(p.y<-40||p.y>H+40)continue;const r=Math.max(5,it.diameter/2*lw/300),edible=it.kind==='food'&&R.canSwallow(g.diameter,it.diameter,g.overdriveTime>0);ctx.save();ctx.translate(p.x,p.y);if(it.kind==='hazard'){ctx.fillStyle='#e94b35';ctx.rotate(-.2);ctx.fillRect(-r,-r,r*2,r*2);ctx.strokeStyle='#f3e8ca';ctx.lineWidth=4;for(let s=-r*2;s<r*2;s+=9){ctx.beginPath();ctx.moveTo(s,-r);ctx.lineTo(s+r*2,r);ctx.stroke()}ctx.fillStyle='#17263b';ctx.font='900 '+Math.max(12,r)+'px Arial';ctx.textAlign='center';ctx.fillText('×',0,r*.45)}else if(it.kind==='capsule'){ctx.fillStyle='#f6c945';ctx.shadowColor='#f6c945';ctx.shadowBlur=15;ctx.roundRect(-r,-r*1.4,r*2,r*2.8,r);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#2862c9';ctx.beginPath();ctx.arc(0,-r*.45,r*.35,0,7);ctx.fill();ctx.fillRect(-r*.4,0,r*.8,r*.75)}else{ctx.fillStyle=colors[(it.id.charCodeAt(it.id.length-1)+g.wave)%5];ctx.beginPath();ctx.arc(0,0,r,0,7);ctx.fill();ctx.strokeStyle=edible?'#71c5a6':'#e7a622';ctx.lineWidth=edible?5:4;ctx.stroke();if(!edible){ctx.fillStyle='#17263b';ctx.font='900 '+Math.max(10,r)+'px Arial';ctx.textAlign='center';ctx.fillText('🔒',0,r*.35)}}ctx.strokeStyle='#17263b';ctx.lineWidth=2.5;ctx.stroke();ctx.restore();if(g.tutorial>0){const key=it.kind==='food'?(edible?'food':null):it.kind;if(key&&!annotated[key]){annotated[key]=true;drawObjectLabel(p.x,p.y-r-8,key==='food'?'먹기 +슛':key==='hazard'?'✕ 피하기':'크루 +3 = 슛 증가',key==='hazard'?'#e94b35':key==='capsule'?'#f6c945':'#71c5a6',annotated.bounds)}}}
for(let i=0;i<g.gates.length;i++){const gate=g.gates[i],p=xy(lx,lw,0,gate.y-g.waveTime);if(p.y<-80||p.y>H+80||g.gateTaken[i])continue;drawGate(lx,p.y,lw,gate)}drawPortal(lx,lw);if(g.tutorial>0){drawObjectLabel(W/2+g.lane*lw*.42,H*.68-26,'내 구멍 · 좌우 이동','#f3e8ca',annotated.bounds);annotated.portal=true;lastVisual.tutorial=annotated}else lastVisual.tutorial=null}
function drawObjectLabel(x,y,text,color,bounds){ctx.save();ctx.font='900 12px Arial';const w=Math.min(W-16,ctx.measureText(text).width+16),left=Math.max(8,Math.min(W-w-8,x-w/2)),top=Math.max(145,Math.min(H-34,y-26));ctx.fillStyle=color;ctx.strokeStyle='#17263b';ctx.lineWidth=2;ctx.fillRect(left,top,w,22);ctx.strokeRect(left,top,w,22);ctx.fillStyle='#17263b';ctx.textAlign='center';ctx.fillText(text,left+w/2,top+15);ctx.beginPath();ctx.moveTo(x,top+22);ctx.lineTo(x,y);ctx.stroke();ctx.restore();bounds.push({left,right:left+w,top,bottom:top+22,text})}
function drawGate(lx,y,lw,gate){const opts=[gate.left,gate.right];for(let i=0;i<2;i++){const x=lx+i*lw/2,result=R.projectGate(g,g.wave,opts[i]),label=opts[i]==='crew'?'크루 +8 / ':opts[i]==='volley'?'발리 ×2 / ':'집중 + / ';ctx.fillStyle=i?'#f6c945':'#71c5a6';ctx.fillRect(x+5,y-32,lw/2-10,64);ctx.strokeStyle='#17263b';ctx.lineWidth=4;ctx.strokeRect(x+5,y-32,lw/2-10,64);ctx.fillStyle='#17263b';ctx.font='900 '+Math.min(17,lw/27)+'px Arial';ctx.textAlign='center';ctx.fillText(label+result.toLocaleString()+'발',x+lw/4,y+6)}}
function drawPortal(lx,lw){const x=lx+lw/2+g.lane*lw*.42,y=H*.68,r=Math.max(W<=620?16:18,g.diameter*lw/510),ry=r*.52;lastVisual.portalWidth=r*2;lastVisual.portalHeight=ry*2;ctx.fillStyle='rgba(0,0,0,.25)';ctx.beginPath();ctx.ellipse(x+5,y+8,r*1.1,ry,0,0,7);ctx.fill();ctx.fillStyle='#05070a';ctx.beginPath();ctx.ellipse(x,y,r,ry,0,0,7);ctx.fill();ctx.strokeStyle=g.overdriveTime>0?'#f6c945':'#f3e8ca';ctx.lineWidth=g.overdriveTime>0?7:3;ctx.stroke()}
function drawCrew(lx,lw){const max=Math.min(48,g.crew),form=R.formation(max),baseX=lx+lw/2+g.lane*lw*.35,baseY=H*.77,scale=W<=620?1.28:1.4;for(let i=form.length-1;i>=0;i--){const m=form[i],x=baseX+m.x*1.65,y=baseY+m.y*.78;ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.fillStyle=m.archetype==='launcher'?'#e94b35':m.archetype==='twin-popper'?'#2862c9':'#f6c945';ctx.strokeStyle='#f3e8ca';ctx.lineWidth=1.5/scale;ctx.beginPath();if(m.archetype==='launcher'){ctx.rect(-3,-8,6,12);ctx.rect(1,-10,7,3)}else if(m.archetype==='twin-popper'){ctx.arc(0,-4,5,0,7);ctx.rect(-7,-9,4,8);ctx.rect(3,-9,4,8)}else{ctx.moveTo(0,-11);ctx.lineTo(7,4);ctx.lineTo(-7,4);ctx.closePath()}ctx.fill();ctx.stroke();ctx.restore()}if(g.crew>48){ctx.fillStyle='#f3e8ca';ctx.font='900 14px Arial';ctx.textAlign='center';ctx.fillText('+'+(g.crew-48)+' MORE',baseX,baseY+55)}}
function drawGoal(lx,lw){const goalY=Math.max(285,H*.42),goalW=lw*.72;ctx.strokeStyle='#f3e8ca';ctx.lineWidth=9;ctx.strokeRect(W/2-goalW/2,goalY,goalW,Math.min(125,H*.22));ctx.strokeStyle='#71c5a6';ctx.lineWidth=2;for(let x=W/2-goalW/2;x<=W/2+goalW/2;x+=16){ctx.beginPath();ctx.moveTo(x,goalY);ctx.lineTo(x,goalY+Math.min(125,H*.22));ctx.stroke()}for(let y=goalY;y<goalY+125;y+=14){ctx.beginPath();ctx.moveTo(W/2-goalW/2,y);ctx.lineTo(W/2+goalW/2,y);ctx.stroke()}if(g.wave===2){const gx=W/2+g.goalie*goalW*.36;ctx.fillStyle='#e94b35';ctx.fillRect(gx-24,goalY+30,48,65);ctx.fillStyle='#f6c945';ctx.beginPath();ctx.arc(gx,goalY+18,17,0,7);ctx.fill();ctx.strokeStyle='#17263b';ctx.lineWidth=3;ctx.stroke();}else{for(const side of[-1,1]){const hx=W/2+side*goalW*.26,hy=goalY+170;ctx.strokeStyle=side<0?'#f6c945':'#e94b35';ctx.lineWidth=8;ctx.beginPath();ctx.ellipse(hx,hy,goalW*.13,18,0,0,7);ctx.stroke();ctx.fillStyle='#f3e8ca';ctx.font='900 13px Arial';ctx.textAlign='center';ctx.fillText('×'+(g.wave+2)+' HOOP',hx,hy-25)}ctx.fillStyle='#e94b35';ctx.strokeStyle='#f3e8ca';ctx.lineWidth=4;ctx.fillRect(W/2-34,goalY+145,68,90);ctx.strokeRect(W/2-34,goalY+145,68,90)}
for(const b of g.balls){if(b.t<0)continue;const ease=b.t,aimX=W/2+g.lane*goalW*.38,baseX=W/2+(aimX-W/2)*ease,spread=lw*(.15-.07*ease),x=baseX+b.fan*spread,y=H*.66+(goalY+60-H*.66)*ease,r=6+g.wave*.8;ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();ctx.strokeStyle='#17263b';ctx.lineWidth=2;ctx.stroke()}}
function drawFX(lx,lw){for(const p of g.particles){ctx.fillStyle=p.color;ctx.fillRect(W/2+p.x*lw*.4,H*.63+p.y,6,9)}for(const s of g.stamps){ctx.save();ctx.translate(W/2,H*.48);ctx.rotate(-.08);ctx.globalAlpha=Math.min(1,s.life*2);ctx.fillStyle=s.color;ctx.strokeStyle='#f3e8ca';ctx.lineWidth=7;ctx.font='900 '+Math.min(72,W/7)+'px Impact,Arial Black';ctx.textAlign='center';ctx.strokeText(s.text,0,0);ctx.fillText(s.text,0,0);ctx.restore()}}
ui.start.addEventListener('click',()=>start());ui.replay.addEventListener('click',()=>start());ui.overdrive.addEventListener('click',overdrive);ui.mute.addEventListener('click',()=>{muted=!muted;ui.mute.textContent=muted?'소리 OFF':'소리 ON';updateUI()});canvas.addEventListener('pointerdown',e=>{initAudio();setLane(e.clientX)});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'||e.buttons)setLane(e.clientX)});addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')g.targetLane=Math.max(-1,g.targetLane-.3);if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')g.targetLane=Math.min(1,g.targetLane+.3);if(e.code==='Space'){e.preventDefault();if(g.state==='title')start();else overdrive()}if(e.key==='p'||e.key==='Escape')pause(g.state!=='paused','manual')});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true,'visibility');else if(g.state==='paused'&&g.pauseSource==='visibility')pause(false,'visibility')});addEventListener('resize',resize);
Object.defineProperty(window,'__GULP_GOAL_DEBUG__',{value:Object.freeze({snapshot:()=>Object.freeze({state:g.state,pausedFrom:g.pausedFrom,pauseSource:g.pauseSource,seed:g.seed,wave:g.wave,phase:g.phase,clarityPhase:g.phase,phaseTime:g.phaseTime,launchTime:g.launchTime,waveTime:g.waveTime,feedProgress:R.feedProgress(g.waveTime),nextShot:g.preparedShotCount!==null?g.preparedShotCount:R.previewVolley(g,g.wave),preparedShotCount:g.preparedShotCount,shotBonus:g.shotBonus,gateProjections:g.gates.map((gate,i)=>g.gateTaken[i]?null:{left:R.projectGate(g,g.wave,gate.left),right:R.projectGate(g,g.wave,gate.right)}),tallyTime:g.tallyTime,lane:g.lane,targetLane:g.targetLane,diameter:g.diameter,crew:g.crew,combo:g.combo,charge:g.overdriveCharge,overdrive:g.overdriveTime,volleyArmed:g.overdriveVolleyArmed,volleyRainbow:g.volleyRainbow,logicalVolley:g.logicalVolley,volleyMultiplier:g.volleyMultiplier,lastCollision:g.lastCollision,lastGate:g.lastGate,attracted:g.attracted,attractionCount:g.attractionCount,goalie:g.goalie,score:g.score,scored:g.scored,need:g.goalNeed,visual:{portalWidth:lastVisual.portalWidth,portalHeight:lastVisual.portalHeight,tutorial:lastVisual.tutorial&&JSON.parse(JSON.stringify(lastVisual.tutorial))},canvas:{cssWidth:W,cssHeight:H,width:canvas.width,height:canvas.height,dpr:DPR}}),startSeeded:seed=>{if(typeof seed==='string'&&seed.length<=40)start(seed)},setPointerLane:x=>{if(Number.isFinite(x))g.targetLane=Math.max(-1,Math.min(1,x))},activateOverdrive:overdrive,advance:seconds=>{let n=Math.min(180,Math.max(0,Number(seconds)||0));while(n>0){step(Math.min(.05,n));n-=.05}},resume:()=>pause(false)}),writable:false,configurable:false});
resize();updateUI();ui.start.focus();raf=requestAnimationFrame(loop);
})();
