/* global TtakPhysics,TtakRules,TtakAI */
'use strict';
const P=TtakPhysics,R=TtakRules,AI=TtakAI,$=s=>document.querySelector(s);
const I18N={
  ko:{title:'딱! 돌판클럽 — TTAK! TABLE CLUB',brand:'딱! 돌판클럽',skip:'게임판으로 건너뛰기',modeListAria:'놀이 선택',staticConnection:'● 정적판',staticOnlineTitle:'온라인 방 사용 불가',staticOnlineDescription:'온라인 방은 서버 빌드가 필요합니다.',marginLeft:'손끝으로 겨루는 돌 한 판',marginRight:'달빛 아래 오래 남는 한 수',eyebrow:'일곱 가지 손맛',homeTitle:'뒤로 당기고,<br><em>딱!</em> 놓으세요.',homeLead:'닳은 한지 위에서 돌과 돌이 맞부딪히는 작은 승부.<br>혼자서도, 한 화면에서도, 온라인 방은 서버 빌드에서 이용할 수 있습니다.',embedHint:'↗ 전체화면 권장 · 아래 놀이는 옆으로 밀어보기',singleEntry:'혼자 두기',singleEntrySub:'인공지능과',localEntry:'마주 두기',localEntrySub:'한 화면에서',back:'← 처음으로',setupEyebrow:'판을 차립니다',setup:'놀이 준비',setupSingle:'혼자 두기',setupLocal:'마주 두기',modeLabel:'놀이',difficultyLabel:'인공지능',playersLabel:'사람/동료 수',amountLabel:'돌 / 목표 수',formationLabel:'진형',coopRuleLabel:'공동 목표',start:'판 벌이기',leave:'← 나가기',pause:'멈춤',resume:'계속',muteOn:'소리 켬',muteOff:'소리 끔',help:'놀이법',thinking:'생각하는 중…',hint:'돌을 누른 채 반대쪽으로 당겨 놓기 · 화살표 조준 · Space 발사',canvas:'돌판. 자신의 돌을 선택하고 반대 방향으로 당겼다가 놓으세요.',helpTitle:'어떻게 놀까요?',helpBody:'내 돌을 누르고 쏠 방향의 반대로 당긴 뒤 놓습니다. 모든 돌이 멈춰야 다음 차례가 옵니다. 기본 대전은 1번 팀이 아래, 2번 팀이 위에서 서로 마주 보는 세로 판입니다.',finished:'판이 끝났습니다',winner:'{player}번 승리!',counter:'도깨비가 반격을 노립니다…',rolling:'돌이 구르는 중…',turn:'{who} 차례 · 돌을 당겨 놓으세요',player:'{player}번',aiPlayer:'2번(AI)',wave:'물결 {wave} · 기회 {budget}',hole:'홀 {hole}/3 · {scores}',round:'제 {round}판',chooseOwn:'내 차례의 돌을 골라주세요',pullMore:'조금 더 당겨주세요',cannotShoot:'지금은 쏠 수 없습니다',easy:'쉬움',normal:'보통',hard:'어려움',standard:'기본진',wedge:'쐐기진',wall:'장벽진',wings:'양날개',otherLanguage:'English',
    resultTitle:'승부 판정',playAgain:'다시 하기',resultHome:'홈으로',
    modes:{classic:{name:'기본 알까기',description:'상대 돌을 모두 판 밖으로 밀어내세요.'},football:{name:'골까기',description:'공을 상대 골문에 넣어 점수를 내세요.'},line:{name:'금 가까이',description:'각자 한 번씩 쏴 선을 넘지 않고 가장 가까이 보내세요.'},golf:{name:'홀인돌',description:'세 홀을 가장 적은 타수로 끝내세요.'},coop:{name:'도깨비 소탕',description:'힘을 합쳐 검은 도깨비 돌을 없애세요.'},royal:{name:'왕좌전',description:'줄어드는 판에서 마지막까지 살아남으세요.'},chain:{name:'연쇄 표적',description:'1번부터 5번 표적을 차례로 맞히세요.'}}},
  en:{title:'TTAK! TABLE CLUB',brand:'TTAK! TABLE CLUB',skip:'Skip to the game board',modeListAria:'Choose a game mode',staticConnection:'● Static build',staticOnlineTitle:'Online rooms unavailable',staticOnlineDescription:'Online rooms require the server build.',marginLeft:'A tabletop duel at your fingertips',marginRight:'One move remembered under moonlight',eyebrow:'SEVEN TABLE TALES',homeTitle:'Pull back,<br>then let it <em>fly!</em>',homeLead:'Seven tactile tabletop games inspired by Korean play.<br>Play solo or share one screen. Online rooms require the server build.',embedHint:'↗ Fullscreen recommended · Swipe the games below',singleEntry:'Single Player',singleEntrySub:'Play against AI',localEntry:'Local Play',localEntrySub:'Share one screen',back:'← Back Home',setupEyebrow:'SET THE TABLE',setup:'Game Setup',setupSingle:'Single Player',setupLocal:'Local Play',modeLabel:'Mode',difficultyLabel:'AI Difficulty',playersLabel:'Players / Allies',amountLabel:'Stones / Target',formationLabel:'Formation',coopRuleLabel:'Cooperative goal',start:'Start Game',leave:'← Leave',pause:'Pause',resume:'Resume',muteOn:'Sound On',muteOff:'Muted',help:'How to Play',thinking:'AI is thinking…',hint:'Drag back and release · Arrow keys aim · Space shoots',canvas:'Game board. Select your stone, drag opposite the shot direction, and release.',helpTitle:'How to Play',helpBody:'Press your stone, pull opposite the direction you want to shoot, then release. The next turn begins after every stone stops. In classic play, Team 1 starts below Team 2 on a vertical board.',finished:'Game over',winner:'Player {player} wins!',counter:'The goblins are preparing a counterattack…',rolling:'Stones are moving…',turn:'{who} turn · Drag a stone and release',player:'Player {player}',aiPlayer:'Player 2 (AI)',wave:'Wave {wave} · Chances {budget}',hole:'Hole {hole}/3 · {scores}',round:'Round {round}',chooseOwn:'Choose a stone from your team.',pullMore:'Pull back a little farther.',cannotShoot:'You cannot shoot right now.',easy:'Easy',normal:'Normal',hard:'Hard',standard:'Standard',wedge:'Wedge',wall:'Wall',wings:'Wings',otherLanguage:'한국어',
    resultTitle:'MATCH RESULT',playAgain:'Play Again',resultHome:'Home',
    modes:{classic:{name:'Classic',description:'Knock every opponent stone off the board.'},football:{name:'Football',description:"Flick the ball into the opponent's goal."},line:{name:'Closest to the Line',description:'Each player shoots once; closest without crossing wins.'},golf:{name:'Stone Golf',description:'Finish three holes in the fewest shots.'},coop:{name:'Goblin Co-op',description:'Work together to clear the black goblin stones.'},royal:{name:'Royal',description:'Stay on the shrinking board until the end.'},chain:{name:'Target Chain',description:'Hit targets 1 through 5 in order.'}}}
};
const storageGet=key=>{try{return localStorage.getItem(key)}catch{return null}},storageSet=(key,value)=>{try{localStorage.setItem(key,value)}catch{}};
let storedLanguage=storageGet('ttak:language');
let language=['ko','en'].includes(storedLanguage)?storedLanguage:'ko';
const t=(key,vars={})=>{let value=key.split('.').reduce((part,name)=>part?.[name],I18N[language]);if(value==null)value=key;return String(value).replace(/\{(\w+)\}/g,(_,name)=>vars[name]??'');};
const names=Object.fromEntries(R.MODES.map(mode=>[mode,[I18N.ko.modes[mode].name,I18N.en.modes[mode].name]]));
const colors=['#a34735','#31485f','#496150','#b98b45'];
let flow='single',game=null,selected=null,aim=null,particles=[],muted=false,paused=false,last=performance.now(),acc=0,aiPending=false,counterPending=false,audio=null,lifecycleEpoch=0;
let replayConfig=null;
const modeCards={};
for(const id of R.MODES){const b=document.createElement('button'),mark=document.createElement('i'),name=document.createElement('b'),description=document.createElement('small');b.className=`mode-mark pigment-${R.MODES.indexOf(id)%4}`;b.dataset.mode=id;description.className='mode-description';b.append(mark);b.append(name);b.append(description);$('#modeList').append(b);modeCards[id]={button:b,name,description};$('#mode').add(new Option('',id));}
const modeList=$('#modeList'),compactEmbed=()=>matchMedia('(max-height:500px) and (min-width:540px) and (orientation:landscape)').matches;
let modeDrag=null,suppressModeClick=false;
modeList.addEventListener('pointerdown',event=>{if(!compactEmbed()||(event.pointerType==='mouse'&&event.button!==0))return;modeDrag={id:event.pointerId,x:event.clientX,scroll:modeList.scrollLeft,moved:false};modeList.setPointerCapture(event.pointerId);modeList.classList.add('dragging');});
modeList.addEventListener('pointermove',event=>{if(!modeDrag||event.pointerId!==modeDrag.id)return;const delta=event.clientX-modeDrag.x;if(Math.abs(delta)>6){modeDrag.moved=true;event.preventDefault();}modeList.scrollLeft=modeDrag.scroll-delta;});
const finishModeDrag=event=>{if(!modeDrag||event.pointerId!==modeDrag.id)return;suppressModeClick=modeDrag.moved;modeList.classList.remove('dragging');if(modeList.hasPointerCapture(event.pointerId))modeList.releasePointerCapture(event.pointerId);modeDrag=null;setTimeout(()=>{suppressModeClick=false;},0);};
modeList.addEventListener('pointerup',finishModeDrag);modeList.addEventListener('pointercancel',finishModeDrag);modeList.addEventListener('click',event=>{if(!suppressModeClick)return;event.preventDefault();event.stopImmediatePropagation();suppressModeClick=false;},true);
const staticText={brand:'brand',embedHint:'embedHint',singleEntry:'singleEntry',singleEntrySub:'singleEntrySub',localEntry:'localEntry',localEntrySub:'localEntrySub',back:'back',setupEyebrow:'setupEyebrow',modeLabel:'modeLabel',difficultyLabel:'difficultyLabel',playersLabel:'playersLabel',amountLabel:'amountLabel',formationLabel:'formationLabel',coopRuleLabel:'coopRuleLabel',start:'start',leave:'leave',pause:'pause',mute:'muteOn',help:'help',thinking:'thinking',hint:'hint',helpTitle:'helpTitle',helpBody:'helpBody',staticOnlineTitle:'staticOnlineTitle',staticOnlineDescription:'staticOnlineDescription',resultTitle:'resultTitle',playAgain:'playAgain',resultHome:'resultHome'};
const staticBuild=true;
function applyLanguage(){document.documentElement.lang=language;document.title=t('title');for(const [id,key] of Object.entries(staticText)){const el=$('#'+id);if(el)el.textContent=t(key);}for(const el of document.querySelectorAll('[data-i18n]'))el.textContent=t(el.dataset.i18n);$('#homeTitle').innerHTML=t('homeTitle');$('#homeLead').innerHTML=t('homeLead');$('#language').textContent=t('otherLanguage');$('#modeList').setAttribute('aria-label',t('modeListAria'));$('#board').setAttribute('aria-label',t('canvas'));$('#helpDialog .close').setAttribute('aria-label',language==='ko'?'닫기':'Close');$('#helpModes').innerHTML=R.MODES.map(id=>`<dt>${t(`modes.${id}.name`)}</dt><dd>${t(`modes.${id}.description`)}</dd>`).join('');const difficulty=$('#difficulty').children;['easy','normal','hard'].forEach((key,index)=>{if(difficulty[index])difficulty[index].text=t(key);});const formation=$('#formation').children;['standard','wedge','wall','wings'].forEach((key,index)=>{if(formation[index])formation[index].text=t(key);});for(const [index,id] of R.MODES.entries()){modeCards[id].name.textContent=t(`modes.${id}.name`);modeCards[id].description.textContent=t(`modes.${id}.description`);$('#mode').children[index].text=t(`modes.${id}.name`);}$('#mute').textContent=t(muted?'muteOff':'muteOn');$('#pause').textContent=t(paused?'resume':'pause');$('#connection').textContent=t('staticConnection');if(flow)$('#setupTitle').textContent=t(flow==='local'?'setupLocal':'setupSingle');if(game){$('#modeTitle').textContent=t(`modes.${game.mode}.name`);announce();}}

$('#language').onclick=()=>{language=language==='ko'?'en':'ko';storageSet('ttak:language',language);applyLanguage();};
applyLanguage();
function show(id){for(const el of ['home','setup','game'])$('#'+el).classList.toggle('hidden',id!==el);if(id==='game')$('#game').focus();}
function syncFormation(){const mode=$('#mode').value,classic=mode==='classic',fixedPair=['classic','football','line'].includes(mode);$('#formationWrap').classList.toggle('hidden',!classic);$('#formation').disabled=!classic;$('#players').disabled=fixedPair;if(fixedPair)$('#players').value='2';}
function configure(f){flow=f;show('setup');$('#difficultyWrap').classList.toggle('hidden',f!=='single');$('.inkbtn').classList.remove('hidden');$('#players').value='2';$('#setupTitle').textContent=t(f==='local'?'setupLocal':'setupSingle');syncFormation();}
document.querySelectorAll('[data-flow]').forEach(b=>b.onclick=()=>configure(b.dataset.flow));document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show('home'));document.querySelectorAll('.mode-mark').forEach(b=>b.onclick=()=>{$('#mode').value=b.dataset.mode;configure('single')});
$('#mode').onchange=syncFormation;
function settings(){const n=+$('#amount').value||5,mode=$('#mode').value;return mode==='classic'?{discs:n,formation:$('#formation').value||'standard'}:mode==='football'?{targetScore:Math.min(9,n)}:mode==='line'?{throws:Math.min(9,n)}:mode==='royal'?{discs:Math.min(8,n)}:mode==='chain'?{turnLimit:Math.max(5,n*3),coop:$('#coopRule').checked}:{}};
$('#setupForm').onsubmit=e=>{e.preventDefault();const m=$('#mode').value;startLocal(m,flow==='single'&&m==='golf'?2:+$('#players').value)};
function resetLifecycle(){lifecycleEpoch++;selected=aim=null;paused=false;aiPending=counterPending=false;acc=0;$('#pause').textContent=t('pause');$('#thinking').classList.add('hidden');$('#resultPanel').classList.add('hidden');}
function startLocal(mode,players,restore){const setup=restore||{mode,players,settings:settings(),difficulty:$('#difficulty').value,flow};replayConfig=typeof structuredClone==='function'?structuredClone(setup):JSON.parse(JSON.stringify(setup));game=R.createGame({mode:setup.mode,players:setup.players,settings:setup.settings});game.ai=setup.flow==='single'&&game.players>1;game.difficulty=setup.difficulty;enterGame();}
function enterGame(){resetLifecycle();show('game');$('#modeTitle').textContent=t(`modes.${game.mode}.name`);resize();announce();}
function resultText(){const result=R.adjudicate(game),single=flow==='single',winner=(result.winner??0)+1,losers=result.defeated.map(i=>i+1);let ko,en;if(result.outcome==='draw'){ko='무승부';en='Draw';}else if(result.outcome==='victory'||single&&result.winner===0){ko='승리';en='Victory';}else if(result.outcome==='defeat'||single){ko='패배';en='Defeat';}else{ko=`${winner}번 승리${losers.length?` · ${losers.map(n=>`${n}번 패배`).join(' · ')}`:''}`;en=`Player ${winner} Wins${losers.length?` · ${losers.map(n=>`Player ${n} Loses`).join(' · ')}`:''}`;}const invalidDistance=language==='ko'?'실격':'invalid',distances=game.attempts?.map(a=>a[0]?.legal?`${Math.round(a[0].distance*10)/10}`:invalidDistance).join(' · '),reasons={classic:['상대 돌을 모두 판 밖으로 밀어냈습니다.','Knocked every opposing stone off the board.'],football:[`최종 점수 ${game.scores.join(' : ')}`,`Final score ${game.scores.join(' : ')}`],line:[`선까지 거리: ${distances}`,`Distances to line: ${distances}`],golf:[`세 홀 타수: ${game.scores.join(' : ')}`,`Three-hole strokes: ${game.scores.join(' : ')}`],coop:[result.outcome==='victory'?'세 물결을 모두 소탕했습니다.':'도깨비를 모두 소탕하지 못했습니다.',result.outcome==='victory'?'Cleared all three waves.':'The goblins were not all cleared.'],royal:['줄어든 판에서 마지막 생존자를 가렸습니다.','The last survivor remained on the shrinking board.'],chain:[`연쇄 표적 점수: ${game.scores.join(' : ')}`,`Target-chain score: ${game.scores.join(' : ')}`]}[game.mode];return{outcome:language==='ko'?ko:en,reason:reasons[language==='ko'?0:1]};}
function renderResult(){const panel=$('#resultPanel');if(!game||game.phase!=='finished'){panel.classList.add('hidden');return;}const firstReveal=panel.classList.contains('hidden'),copy=resultText();$('#resultOutcome').textContent=copy.outcome;$('#resultReason').textContent=copy.reason;panel.classList.remove('hidden');if(firstReveal)$('#playAgain').focus();}
function announce(msg){if(!game)return;const who=game.mode==='golf'&&game.ai&&game.turn===1?t('aiPlayer'):t('player',{player:game.turn+1});$('#status').textContent=msg||(game.phase==='finished'?(game.winner==null?t('finished'):t('winner',{player:game.winner+1})):game.phase==='counter'?t('counter'):game.phase==='simulating'?t('rolling'):t('turn',{who}));$('#score').textContent=game.mode==='coop'?t('wave',{wave:game.wave||1,budget:game.turnBudget}):game.mode==='golf'?t('hole',{hole:(game.hole||0)+1,scores:game.scores.join(' : ')}):game.scores?.some(Boolean)?game.scores.join(' : '):t('round',{round:game.round||1});renderResult();}
const canvas=$('#board'),ctx=canvas.getContext('2d');
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.width*.6*d);ctx.setTransform(canvas.width/1200,0,0,canvas.height/720,0,0);}
addEventListener('resize',resize);
function pointer(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*1200/r.width,y:(e.clientY-r.top)*720/r.height};}
canvas.onpointerdown=e=>{if(!game||game.phase!=='aiming'||paused)return;ensureAudio();const p=pointer(e),legal=R.eligibleObjects(game);const o=legal.find(d=>Math.hypot(d.x-p.x,d.y-p.y)<=d.radius+14);if(!o)return invalid(t('chooseOwn'));selected=o;aim=p;canvas.setPointerCapture(e.pointerId)};
canvas.onpointermove=e=>{if(aim)aim=pointer(e)};
canvas.onpointercancel=()=>{selected=aim=null;};
canvas.onpointerup=e=>{if(!selected||!aim)return;const force={x:(selected.x-aim.x)*7.2,y:(selected.y-aim.y)*7.2},mag=Math.hypot(force.x,force.y);if(mag<80){selected=aim=null;return invalid(t('pullMore'));}if(mag>P.MAX_SPEED){force.x*=P.MAX_SPEED/mag;force.y*=P.MAX_SPEED/mag;}fire(selected.id,force);selected=aim=null;};
function fire(id,force){clack(.12,0);if(!R.markShot(game,id))return invalid(t('cannotShoot'));P.applyShot(game.objects.find(o=>o.id===id),force);announce();}
function invalid(msg){announce(msg);canvas.classList.add('impact');setTimeout(()=>canvas.classList.remove('impact'),180);clack(.04,-400);}
function simulation(dt){if(!game||paused||game.phase!=='simulating')return;acc+=Math.min(dt,.05);let events=[];while(acc>=1/120){events.push(...P.step(game.objects,1/120,game.board));acc-=1/120;}P.accumulateEvents(game.pendingEvents||(game.pendingEvents=[]),events);for(const e of events)if(e.type==='impact'){burst(e.x,e.y,e.strength);clack(Math.min(.18,e.strength/2000),(e.x/1200-.5)*500)}if(P.allResting(game.objects)){R.resolve(game,P.consumeEvents(game));announce();if(game.phase==='counter')scheduleGoblinCounter();else if(game.ai&&game.phase==='aiming'&&game.turn>0){const lifecycleToken=lifecycleEpoch;setTimeout(()=>{if(lifecycleToken===lifecycleEpoch)aiTurn()},450);}}}
function scheduleGoblinCounter(){if(counterPending||!game||game.phase!=='counter')return;const lifecycleToken=lifecycleEpoch;counterPending=true;announce(t('counter'));const runCounter=()=>{if(lifecycleToken!==lifecycleEpoch)return;if(paused){setTimeout(runCounter,100);return;}counterPending=false;if(!game||game.phase!=='counter')return;const s=AI.chooseGoblinShot(game,game.shot*4099+game.wave);if(s&&R.beginGoblinCounter(game,s.id)){const attacker=game.objects.find(o=>o.id===s.id);P.applyShot(attacker,s.force);burst(attacker.x,attacker.y,240);announce();}};setTimeout(runCounter,500);}
function aiTurn(){if(!game||game.phase!=='aiming'||game.turn===0||aiPending)return;const lifecycleToken=lifecycleEpoch;aiPending=true;$('#thinking').classList.remove('hidden');const runAI=()=>{if(lifecycleToken!==lifecycleEpoch)return;if(paused){setTimeout(runAI,100);return;}const s=AI.chooseShot(game,game.difficulty);aiPending=false;$('#thinking').classList.add('hidden');if(s)fire(s.id,s.force)};requestAnimationFrame(()=>setTimeout(runAI,250));}
function burst(x,y,power){for(let i=0;i<Math.min(10,2+power/100);i++)particles.push({x,y,vx:(Math.random()-.5)*power*.3,vy:(Math.random()-.5)*power*.3,life:1});}
function paper(){ctx.fillStyle='#e7dcc1';ctx.fillRect(0,0,1200,720);ctx.globalAlpha=.1;for(let i=0;i<90;i++){ctx.strokeStyle=i%3?'#594a37':'#9a4735';ctx.beginPath();const y=(i*83)%720;ctx.moveTo((i*137)%1200,y);ctx.quadraticCurveTo(600,y+(i%5-2)*4,1200,y+2);ctx.stroke()}ctx.globalAlpha=1;ctx.strokeStyle='#24211d55';ctx.lineWidth=3;ctx.setLineDash([14,9]);if(game.mode==='line'){ctx.beginPath();ctx.moveTo(34,34);ctx.lineTo(34,686);ctx.lineTo(1166,686);ctx.lineTo(1166,34);ctx.stroke();}else ctx.strokeRect(34,34,1132,652);ctx.setLineDash([]);}
function motif(){ctx.save();ctx.strokeStyle='#31485f55';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(55,620);ctx.bezierCurveTo(100,575,130,650,170,602);ctx.bezierCurveTo(205,566,235,630,270,600);ctx.stroke();ctx.translate(1070,82);ctx.beginPath();ctx.ellipse(0,0,45,23,-.2,0,7);ctx.moveTo(-38,3);ctx.quadraticCurveTo(-70,18,-82,4);ctx.moveTo(33,-7);ctx.lineTo(58,-25);ctx.stroke();ctx.restore();}
function modeArt(){const b=game.board;ctx.save();if(game.mode==='classic'){const q=b.geometry.grid,f=b.geometry.frame;ctx.fillStyle='#c79a58';ctx.fillRect(0,0,1200,720);ctx.strokeStyle='#7a4d27';ctx.globalAlpha=.22;ctx.lineWidth=2;for(let i=0;i<34;i++){const y=18+i*21;ctx.beginPath();ctx.moveTo(18,y);ctx.bezierCurveTo(270,y+(i%5-2)*5,760,y+(i%7-3)*4,1182,y+(i%4-2)*3);ctx.stroke();}ctx.globalAlpha=1;ctx.strokeStyle='#5b351d';ctx.lineWidth=18;ctx.strokeRect(f.x,f.y,f.w,f.h);ctx.strokeStyle='#262019';ctx.lineWidth=2;for(let i=0;i<q.lines;i++){const p=i*q.spacing;ctx.beginPath();ctx.moveTo(q.left+p,q.top);ctx.lineTo(q.left+p,q.top+q.spacing*18);ctx.moveTo(q.left,q.top+p);ctx.lineTo(q.left+q.spacing*18,q.top+p);ctx.stroke();}ctx.fillStyle='#262019';for(const star of b.geometry.stars){ctx.beginPath();ctx.arc(q.left+star.column*q.spacing,q.top+star.row*q.spacing,5,0,7);ctx.fill();}}
if(game.mode==='football'){const f=b.geometry;ctx.fillStyle='#27362e';ctx.fillRect(0,0,1200,720);ctx.fillStyle='#496846';ctx.fillRect(f.touchline.x,f.touchline.y,f.touchline.w,f.touchline.h);const stripeW=f.touchline.w/10;for(let i=0;i<10;i++){ctx.fillStyle=i%2?'#52744d':'#466743';ctx.fillRect(f.touchline.x+i*stripeW,f.touchline.y,stripeW,f.touchline.h);}ctx.globalAlpha=.13;ctx.strokeStyle='#d8d0ad';ctx.lineWidth=2;for(let i=0;i<18;i++){const x=f.touchline.x+(i*97)%f.touchline.w;ctx.beginPath();ctx.moveTo(x,f.touchline.y);ctx.lineTo(Math.min(f.touchline.x+f.touchline.w,x+34),f.touchline.y+f.touchline.h);ctx.stroke();}ctx.globalAlpha=1;ctx.strokeStyle='#eee8d1';ctx.lineWidth=6;ctx.strokeRect(f.touchline.x,f.touchline.y,f.touchline.w,f.touchline.h);ctx.beginPath();ctx.moveTo(f.touchline.x,f.halfway.y);ctx.lineTo(f.touchline.x+f.touchline.w,f.halfway.y);ctx.arc(f.center.x,f.center.y,f.center.radius,0,7);ctx.stroke();ctx.fillStyle='#eee8d1';ctx.beginPath();ctx.arc(f.center.x,f.center.y,6,0,7);ctx.fill();for(const box of f.penaltyBoxes)ctx.strokeRect(box.x,box.y,box.w,box.h);const goalDepth=18,top=f.touchline.y,bottom=f.touchline.y+f.touchline.h;ctx.lineWidth=4;ctx.strokeRect(f.goals.x1,top-goalDepth,f.goals.x2-f.goals.x1,goalDepth);ctx.strokeRect(f.goals.x1,bottom,f.goals.x2-f.goals.x1,goalDepth);for(let x=f.goals.x1+20;x<f.goals.x2;x+=20){ctx.beginPath();ctx.moveTo(x,top-goalDepth);ctx.lineTo(x,top);ctx.moveTo(x,bottom);ctx.lineTo(x,bottom+goalDepth);ctx.stroke();}}
if(game.mode==='line'){for(let x=80;x<1150;x+=42){ctx.beginPath();ctx.moveTo(x,50);ctx.lineTo(x,670);ctx.strokeStyle='#49615033';ctx.lineWidth=3;ctx.stroke();}ctx.strokeStyle='#a34735';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(65,b.targetLine);ctx.lineTo(1135,b.targetLine);ctx.stroke();ctx.strokeStyle='#5b351d';ctx.lineWidth=18;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(34,34);ctx.lineTo(34,686);ctx.lineTo(1166,686);ctx.lineTo(1166,34);ctx.stroke();ctx.lineCap='butt';}
if(game.mode==='golf'){ctx.fillStyle='#3f5e3f';ctx.fillRect(0,0,1200,720);ctx.fillStyle='#79915b';ctx.beginPath();(b.fairway||[]).forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fill();ctx.strokeStyle='#314b35';ctx.lineWidth=3;ctx.stroke();for(const z of b.rough||[]){ctx.fillStyle='#304d37';ctx.fillRect(z.x,z.y,z.w,z.h);ctx.strokeStyle='#91a26a55';ctx.lineWidth=2;for(let x=z.x;x<z.x+z.w;x+=18){ctx.beginPath();ctx.moveTo(x,z.y+z.h);ctx.lineTo(x+9,z.y);ctx.stroke();}}const green=b.puttingGreen;ctx.fillStyle='#9caf72';ctx.globalAlpha=.78;ctx.beginPath();ctx.ellipse(green.x,green.y,green.rx,green.ry,.04,0,7);ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle='#516b43';ctx.lineWidth=2;ctx.stroke();for(const z of b.bunkers||[]){ctx.fillStyle='#d2b875';ctx.beginPath();ctx.ellipse(z.x,z.y,z.rx,z.ry,-.12,0,7);ctx.fill();ctx.strokeStyle='#6f633f';ctx.stroke();}for(const r of b.rocks||[]){ctx.fillStyle='#655d50';ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,7);ctx.fill();ctx.strokeStyle='#29241f';ctx.stroke();}ctx.fillStyle='#24211d';ctx.beginPath();ctx.arc(b.cup.x,b.cup.y,b.cup.r,0,7);ctx.fill();ctx.strokeStyle='#a34735';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(b.cup.x,b.cup.y);ctx.lineTo(b.cup.x,b.cup.y-90);ctx.lineTo(b.cup.x+55,b.cup.y-70);ctx.lineTo(b.cup.x,b.cup.y-52);ctx.stroke();}if(game.mode==='royal'){ctx.strokeStyle='#a34735';ctx.lineWidth=10;ctx.strokeRect(b.inset,b.inset,1200-b.inset*2,720-b.inset*2);}ctx.restore();}
function drawDisc(o){if(o.kind==='rock')return;ctx.save();ctx.translate(o.x,o.y);const moving=Math.hypot(o.vx,o.vy)>20;if(moving)ctx.scale(1.06,.94);ctx.fillStyle=o.kind==='goblin'?'#24211d':o.kind==='ball'?'#eee8d1':o.kind==='target'?'#e7dcc1':colors[o.team%4]||'#24211d';ctx.strokeStyle='#24211d';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,o.radius,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.globalAlpha=.35;ctx.beginPath();ctx.arc(-3,2,o.radius-8,.2,5.7);ctx.strokeStyle='#e7dcc1';ctx.lineWidth=2;ctx.stroke();ctx.globalAlpha=1;ctx.fillStyle=o.kind==='goblin'?'#e7dcc1':'#24211d';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`900 ${o.radius*.9}px serif`;ctx.fillText(o.kind==='target'?o.number:o.kind==='goblin'?(o.heavy?'王':'鬼'):o.kind==='ball'?'●':(o.team??0)+1,0,2);if(o.kind==='goblin'){ctx.beginPath();ctx.moveTo(-16,-o.radius+5);ctx.lineTo(-8,-o.radius-12);ctx.lineTo(0,-o.radius+2);ctx.moveTo(7,-o.radius+3);ctx.lineTo(17,-o.radius-10);ctx.lineTo(19,-o.radius+8);ctx.stroke();}ctx.restore();}
function render(dt){if(game){paper();motif();modeArt();for(const o of game.objects)if(o.active)drawDisc(o);if(selected&&aim){const dx=selected.x-aim.x,dy=selected.y-aim.y,m=Math.min(210,Math.hypot(dx,dy));ctx.strokeStyle='#a34735';ctx.lineWidth=5;ctx.setLineDash([13,8]);ctx.beginPath();ctx.moveTo(selected.x,selected.y);ctx.lineTo(aim.x,aim.y);ctx.stroke();ctx.setLineDash([]);const a=Math.atan2(dy,dx);ctx.globalAlpha=.35;for(let i=1;i<6;i++){ctx.beginPath();ctx.arc(selected.x+Math.cos(a)*i*45,selected.y+Math.sin(a)*i*45,6-i*.6,0,7);ctx.fillStyle='#a34735';ctx.fill();}ctx.globalAlpha=1;for(let i=1;i<=5;i++){ctx.fillStyle=i*42<m?'#a34735':'#24211d44';ctx.fillRect(50+i*20,670,13,-i*7);}}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt*2;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle='#6d5540';ctx.fillRect(p.x,p.y,3,3)}ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0);}}
function frame(now){const dt=(now-last)/1000;last=now;simulation(dt);render(dt);requestAnimationFrame(frame)}requestAnimationFrame(frame);
function ensureAudio(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();}
function clack(gain=.1,pan=0){if(muted)return;ensureAudio();const o=audio.createOscillator(),g=audio.createGain(),f=audio.createBiquadFilter();o.type='triangle';o.frequency.setValueAtTime(260+pan*.1,audio.currentTime);o.frequency.exponentialRampToValueAtTime(70,audio.currentTime+.07);f.type='bandpass';f.frequency.value=850+pan;g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.1);o.connect(f).connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.11)}
$('#mute').onclick=()=>{muted=!muted;$('#mute').textContent=t(muted?'muteOff':'muteOn');$('#mute').setAttribute('aria-pressed',muted)};$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=t(paused?'resume':'pause')};$('#leave').onclick=()=>{resetLifecycle();game=null;show('home')};
$('#playAgain').onclick=()=>{if(!game)return;if(game.authoritative){$('#leave').onclick();configure(flow);return;}startLocal(replayConfig.mode,replayConfig.players,replayConfig)};
$('#resultHome').onclick=()=>$('#leave').onclick();
$('#help').onclick=()=>$('#helpDialog').showModal();$('#helpDialog .close').onclick=()=>$('#helpDialog').close();
document.onkeydown=e=>{if(!game||game.phase!=='aiming')return;const legal=R.eligibleObjects(game);if(!selected)selected=legal[0];if(!selected)return;if(!aim)aim={x:selected.x-100,y:selected.y};const key={ArrowLeft:[-12,0],ArrowRight:[12,0],ArrowUp:[0,-12],ArrowDown:[0,12]}[e.key];if(key){e.preventDefault();aim.x+=key[0];aim.y+=key[1]}if(e.code==='Space'){e.preventDefault();fire(selected.id,{x:(selected.x-aim.x)*7.2,y:(selected.y-aim.y)*7.2});selected=aim=null;}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
const safeState=()=>game?Object.freeze({mode:game.mode,formation:game.settings?.formation||null,orientation:game.board.orientation||null,phase:game.phase,turn:game.turn,objects:game.objects.filter(o=>o.active).length,connection:'local'}):Object.freeze({mode:null,formation:null,orientation:null,phase:'lobby',turn:null,objects:0,connection:'local'});
const selectMode=m=>{if(!R.MODES.includes(m))return false;$('#mode').value=m;syncFormation();return true};
window.__TTAK__=Object.freeze({state:safeState,selectMode,startSingle:(m='classic',d='normal')=>{flow='single';m=R.MODES.includes(m)?m:'classic';selectMode(m);$('#difficulty').value=d;startLocal(m,2);return safeState()},fireLegal:()=>{const o=game&&R.eligibleObjects(game)[0];if(!o)return false;fire(o.id,{x:650,y:0});return true},counts:()=>safeState()});
