window.TTAK_GUIDE_LOCALES={
  es:{name:'Español',ui:{button:'? Guía en 30 s',eyebrow:'GUÍA EN 30 S',close:'Cerrar guía',done:'Entendido',inGame:'Guía del juego actual',tip:'Consejo rápido'},labels:['OBJETIVO','TU JUGADA','VICTORIA'],modeNames:{classic:'Clásico',football:'Fútbol',line:'Cerca de la línea',golf:'Golf de piedras',coop:'Caza de dokkaebi',royal:'Batalla real',chain:'Cadena de objetivos'},modes:{
    classic:{steps:['Expulsa del tablero todas las fichas rivales.','Mantén pulsada tu ficha, tira hacia atrás en sentido opuesto al disparo y suelta.','Ganas si quedan fichas tuyas y no queda ninguna rival.'],tip:'Un golpe lateral de refilón suele expulsar una ficha con menos fuerza.'},
    football:{steps:['Mete el balón en la portería rival usando tus fichas.','Golpea el balón con una ficha y aprovecha los rebotes en las paredes.','Gana quien alcance primero la puntuación fijada.'],tip:'No te limites a golpear fuerte: deja fichas bien colocadas para la siguiente jugada.'},
    line:{steps:['Deja tu ficha lo más cerca posible de la línea sin cruzarla.','Cada jugador lanza una vez su propia ficha.','Gana quien deje la ficha válida más cercana a la línea.'],tip:'Empieza con suavidad y calcula cuánto frenará la fricción.'},
    golf:{steps:['Emboca tu ficha y completa los tres hoyos.','Da un golpe por turno y evita rocas y zonas que frenan la ficha.','Gana quien complete los tres hoyos con menos golpes.'],tip:'Busca una ruta amplia y segura si el tiro directo complica el siguiente golpe.'},
    coop:{steps:['Colaboren para eliminar todas las piedras negras de los duendes.','Por turnos, lancen sus fichas para expulsar a los duendes del tablero.','Eliminen las tres oleadas antes de agotar las jugadas o perder todas sus fichas.'],tip:'El duende más grande pesa más; empújenlo varias veces con distintas fichas.'},
    royal:{steps:['Sobrevive hasta el final en un tablero que se reduce cada ronda.','Protege tus fichas y empuja a tus rivales hacia el borde peligroso.','Ganas cuando solo quedan fichas de tu equipo en el tablero.'],tip:'Controlar el centro te mantiene a salvo cuando el borde se cierra.'},
    chain:{steps:['Golpea los objetivos del 1 al 5 en orden.','Lanza tu ficha contra el objetivo que muestra el número actual.','La partida termina al acertar el 5 o agotar las jugadas; gana la puntuación más alta y un empate queda en tablas.'],coopWin:'Alcancen juntos el objetivo 5 antes de agotar el límite común de jugadas.',tip:'Un objetivo fuera de orden no hace avanzar la cadena; comprueba siempre el número actual.'}
  }},
  'pt-BR':{name:'Português (Brasil)',ui:{button:'? Guia em 30 s',eyebrow:'GUIA EM 30 S',close:'Fechar guia',done:'Entendi',inGame:'Guia do jogo atual',tip:'Dica rápida'},labels:['OBJETIVO','SUA JOGADA','VITÓRIA'],modeNames:{classic:'Clássico',football:'Futebol',line:'Mais perto da linha',golf:'Golfe de pedras',coop:'Caça aos dokkaebi',royal:'Batalha real',chain:'Sequência de alvos'},modes:{
    classic:{steps:['Tire do tabuleiro todas as pedras adversárias.','Pressione sua pedra, puxe no sentido oposto ao lançamento e solte.','Você vence se restarem pedras suas e nenhuma adversária.'],tip:'Uma batida lateral de raspão costuma expulsar a pedra com menos força.'},
    football:{steps:['Faça a bola entrar no gol adversário usando suas pedras.','Use uma pedra para empurrar a bola e aproveite as tabelas nas paredes.','Vence quem alcançar primeiro a pontuação definida.'],tip:'Não bata só com força: deixe suas pedras bem posicionadas para a próxima jogada.'},
    line:{steps:['Pare sua pedra o mais perto possível da linha, sem ultrapassá-la.','Cada jogador lança a própria pedra uma vez.','Vence quem deixar a pedra válida mais próxima da linha.'],tip:'Comece devagar e calcule quanto a fricção vai frear a pedra.'},
    golf:{steps:['Coloque sua pedra no buraco e complete os três percursos.','Dê uma tacada por turno e evite pedras e áreas que reduzem a velocidade.','Vence quem completar os três buracos com menos tacadas.'],tip:'Escolha uma rota ampla e segura se o caminho direto dificultar a próxima tacada.'},
    coop:{steps:['Trabalhem juntos para eliminar todas as pedras pretas dos goblins.','Em turnos, lancem suas pedras para empurrar os goblins para fora.','Eliminem as três ondas antes de acabarem as jogadas ou todas as pedras da equipe.'],tip:'O goblin maior é pesado; empurre-o várias vezes com pedras diferentes.'},
    royal:{steps:['Sobreviva até o fim em um tabuleiro que encolhe a cada rodada.','Proteja suas pedras e empurre os rivais para a borda perigosa.','Você vence quando só restam pedras da sua equipe no tabuleiro.'],tip:'Dominar o centro mantém você mais seguro quando a borda se fecha.'},
    chain:{steps:['Acerte os alvos de 1 a 5 na ordem.','Lance sua pedra contra o alvo que mostra o número atual.','A partida acaba ao acertar o 5 ou esgotar as jogadas; vence a maior pontuação e empate é declarado.'],coopWin:'Alcancem juntos o alvo 5 antes de esgotar o limite coletivo de jogadas.',tip:'Um alvo fora da ordem não avança a sequência; confira sempre o número atual.'}
  }},
  de:{name:'Deutsch',ui:{button:'? 30-Sekunden-Anleitung',eyebrow:'IN 30 SEKUNDEN ERKLÄRT',close:'Anleitung schließen',done:'Verstanden',inGame:'Anleitung zum aktuellen Spiel',tip:'Kurztipp'},labels:['ZIEL','DEIN ZUG','SIEG'],modeNames:{classic:'Klassisch',football:'Fußball',line:'Nah an die Linie',golf:'Steingolf',coop:'Dokkaebi-Jagd',royal:'Königskampf',chain:'Zielkette'},modes:{
    classic:{steps:['Stoße alle gegnerischen Steine vom Brett.','Drücke deinen Stein, ziehe entgegen der Schussrichtung und lass los.','Du gewinnst, wenn nur noch Steine deines Teams auf dem Brett liegen.'],tip:'Ein seitlicher Streifschuss befördert Steine oft mit weniger Kraft hinaus.'},
    football:{steps:['Spiele den Ball mit deinen Steinen ins gegnerische Tor.','Schieße einen Stein gegen den Ball und nutze die Bande für gute Winkel.','Wer zuerst die gewählte Zielpunktzahl erreicht, gewinnt.'],tip:'Schlage nicht nur fest: Lass deine Steine auch günstig für den nächsten Zug liegen.'},
    line:{steps:['Bring deinen Stein so nah wie möglich an die Linie, ohne sie zu überqueren.','Jeder spielt genau einen Schuss mit dem eigenen Stein.','Der gültige Stein mit dem kleinsten Abstand gewinnt; Gleichstand ist remis.'],tip:'Beginne sanft und schätze ab, wie weit der Stein durch die Reibung noch gleitet.'},
    golf:{steps:['Spiele deinen Stein ins Loch und absolviere alle drei Bahnen.','Pro Zug spielst du einmal; meide Felsen und rauen Boden.','Nach drei Löchern gewinnt, wer insgesamt die wenigsten Schläge hat.'],tip:'Wähle lieber einen breiten, sicheren Weg, wenn der direkte Schuss den nächsten erschwert.'},
    coop:{steps:['Vertreibt gemeinsam alle schwarzen Goblin-Steine.','Spielt reihum eure Steine, um die Goblins vom Brett zu stoßen.','Räumt alle drei Wellen, bevor euch Schüsse oder eigene Steine ausgehen.'],tip:'Der größte Goblin ist schwer. Schiebt ihn mehrmals mit verschiedenen Steinen an.'},
    royal:{steps:['Bleib bis zuletzt auf dem Brett, das jede Runde kleiner wird.','Schütze deine Steine und dränge Gegner an den gefährlichen Rand.','Du gewinnst, wenn nur noch Steine deines Teams auf dem Brett liegen.'],tip:'Halte die Mitte: Dort bist du sicherer, wenn der Rand näher rückt.'},
    chain:{steps:['Triff die Ziele 1 bis 5 in der richtigen Reihenfolge.','Schieße deinen Stein gegen das aktuelle Ziel; jeder richtige Treffer bringt einen Punkt.','Ziel 5 oder das Schusslimit beendet die Partie. Die höchste Punktzahl gewinnt; Gleichstand ist remis.'],coopWin:'Trefft gemeinsam Ziel 5, bevor das gemeinsame Schusslimit erreicht ist – dann gewinnen alle.',tip:'Ein falsches Ziel bringt die Kette nicht weiter. Prüfe immer die aktuelle Nummer.'}
  }},
  fr:{name:'Français',ui:{button:'? Guide en 30 s',eyebrow:'GUIDE EN 30 S',close:'Fermer le guide',done:'Compris',inGame:'Guide du jeu en cours',tip:'Astuce'},labels:['OBJECTIF','VOTRE COUP','VICTOIRE'],modeNames:{classic:'Classique',football:'Football',line:'Au plus près de la ligne',golf:'Golf de pierres',coop:'Chasse aux dokkaebi',royal:'Bataille royale',chain:'Chaîne de cibles'},modes:{
    classic:{steps:['Éjectez du plateau toutes les pierres adverses.','Appuyez sur votre pierre, tirez dans le sens opposé au lancer, puis relâchez.','Vous gagnez s’il reste vos pierres et aucune pierre adverse.'],tip:'Un coup latéral en biais éjecte souvent une pierre avec moins de force.'},
    football:{steps:['Envoyez le ballon dans le but adverse avec vos pierres.','Frappez le ballon avec une pierre et utilisez les rebonds sur les parois.','Le premier à atteindre le score choisi gagne.'],tip:'Ne frappez pas seulement fort : placez aussi vos pierres pour le coup suivant.'},
    line:{steps:['Arrêtez votre pierre au plus près de la ligne sans la franchir.','Chaque joueur lance une fois sa propre pierre.','La pierre valide la plus proche de la ligne remporte la partie.'],tip:'Commencez doucement et estimez la distance de freinage.'},
    golf:{steps:['Mettez votre pierre dans le trou et terminez les trois parcours.','Jouez un coup par tour en évitant rochers et zones qui ralentissent la pierre.','Le joueur avec le moins de coups après trois trous gagne.'],tip:'Prenez une voie large et sûre si le tir direct complique le coup suivant.'},
    coop:{steps:['Coopérez pour éliminer toutes les pierres noires des gobelins.','À tour de rôle, éjectez les gobelins avec vos pierres.','Éliminez les trois vagues avant d’épuiser les coups ou toutes vos pierres.'],tip:'Le plus grand gobelin est lourd : poussez-le plusieurs fois avec différentes pierres.'},
    royal:{steps:['Survivez jusqu’au bout sur un plateau qui rétrécit à chaque manche.','Protégez vos pierres et poussez vos rivaux vers le bord dangereux.','Vous gagnez quand seules les pierres de votre équipe restent sur le plateau.'],tip:'Contrôler le centre vous protège quand les limites se resserrent.'},
    chain:{steps:['Touchez les cibles 1 à 5 dans l’ordre.','Lancez votre pierre contre la cible portant le numéro actuel.','La cible 5 ou la limite de coups termine la partie ; le meilleur score gagne et une égalité donne un match nul.'],coopWin:'Atteignez ensemble la cible 5 avant d’épuiser la limite commune de coups.',tip:'Une cible hors séquence ne fait pas avancer la chaîne ; vérifiez le numéro actuel.'}
  }},
  ru:{name:'Русский',ui:{button:'? Правила за 30 секунд',eyebrow:'ПРАВИЛА ЗА 30 СЕКУНД',close:'Закрыть правила',done:'Понятно',inGame:'Правила текущей игры',tip:'Совет'},labels:['ЦЕЛЬ','ХОД','ПОБЕДА'],modeNames:{classic:'Классика',football:'Футбол',line:'Ближе к линии',golf:'Каменный гольф',coop:'Охота на токкэби',royal:'Королевская битва',chain:'Цепочка мишеней'},modes:{
    classic:{steps:['Выбейте все камни соперников с поля.','Нажмите свой камень, оттяните против направления удара и отпустите.','Вы победите, если на поле останутся только камни вашей команды.'],tip:'Касательный удар сбоку часто выбивает камень с меньшей силой.'},
    football:{steps:['Забейте мяч камнями в ворота соперника.','Запустите камень в мяч и используйте отскоки от бортов для удачного угла.','Побеждает тот, кто первым наберёт выбранное число очков.'],tip:'Не бейте только на силу: оставляйте камни в удобных позициях для следующего хода.'},
    line:{steps:['Остановите камень как можно ближе к линии, не пересекая её.','Каждый игрок делает ровно один бросок своим камнем.','Ближайший камень, не пересёкший линию, побеждает; при равенстве — ничья.'],tip:'Начните с лёгкого удара и оцените, как трение замедляет камень.'},
    golf:{steps:['Загоните камень в лунку и пройдите все три лунки.','Делайте по одному удару за ход, обходя камни и участки высокой травы.','После трёх лунок побеждает игрок с наименьшим общим числом ударов.'],tip:'Выбирайте широкий безопасный путь, если прямой удар усложнит следующий.'},
    coop:{steps:['Вместе выбейте все чёрные камни-гоблины.','По очереди запускайте свои камни, выбивая гоблинов с поля.','Очистите три волны, пока не кончились общие броски или ваши камни.'],tip:'Самый большой гоблин тяжёлый. Толкайте его несколько раз разными камнями.'},
    royal:{steps:['Продержитесь до конца на поле, которое сужается каждый раунд.','Берегите свои камни и выталкивайте соперников к опасному краю.','Вы победите, если на поле останутся только камни вашей команды.'],tip:'Держитесь центра: там безопаснее, когда границы сдвигаются.'},
    chain:{steps:['Поразите цели с 1-й по 5-ю строго по порядку.','Попадите своим камнем в текущую цель: верное попадание приносит очко.','Игра закончится после цели 5 или по лимиту бросков. Победит набравший больше всех; при равенстве — ничья.'],coopWin:'Вместе поразите цель 5 до исчерпания общего лимита бросков — и победят все.',tip:'Попадание не в ту цель не продолжает цепочку. Всегда сверяйтесь с текущим номером.'}
  }},
  ja:{name:'日本語',ui:{button:'? 30秒ガイド',eyebrow:'30秒ガイド',close:'ガイドを閉じる',done:'わかった',inGame:'このゲームのガイド',tip:'ワンポイント'},labels:['目的','操作','勝利'],modeNames:{classic:'ベーシック',football:'サッカー',line:'ラインぎりぎり',golf:'ストーンゴルフ',coop:'トッケビ退治',royal:'王座戦',chain:'連続ターゲット'},modes:{
    classic:{steps:['相手の石をすべて盤外へ弾き出そう。','自分の石をタッチし、飛ばす方向と逆へ引いて離します。','自分の石が残り、相手の石がすべてなくなれば勝ち。'],tip:'正面より側面をかすめるように当てると、弱い力でも押し出しやすくなります。'},
    football:{steps:['自分の石でボールを弾き、相手ゴールに入れよう。','石をフリックしてボールを押し、壁の跳ね返りで角度を作ります。','設定した目標点に先に到達すれば勝ち。'],tip:'強く当てるだけでなく、次に使いやすい位置へ石を残しましょう。'},
    line:{steps:['ラインを越えず、できるだけ近くに石を止めよう。','各プレイヤーが自分の石を1回ずつ飛ばします。','ライン手前の有効な石のうち、最も近い石が勝ち。'],tip:'最初は弱めに飛ばし、摩擦で止まる距離をつかみましょう。'},
    golf:{steps:['石をカップに入れ、全3ホールを回ろう。','岩やラフ、壁を避けながら、各ターンに1打します。','3ホールの合計打数が最も少ないプレイヤーが勝ち。'],tip:'直線狙いで次が難しくなるなら、広く安全なルートを選びましょう。'},
    coop:{steps:['仲間と協力し、黒い鬼の石をすべて退治しよう。','交代で自分の石を弾き、鬼を盤外へ押し出します。','手数か味方の石が尽きる前に全3ウェーブをクリアすれば、全員の勝ち。'],tip:'一番大きな鬼は重いので、複数の石で繰り返し押しましょう。'},
    royal:{steps:['ラウンドごとに縮む盤で、最後まで生き残ろう。','自分の石を守りながら、相手を危険な端へ押し出します。','盤上に自分のチームの石だけが残れば勝ち。'],tip:'中央を取ると、盤が縮んでも生き残りやすくなります。'},
    chain:{steps:['1番から5番まで、数字の順にターゲットを当てよう。','自分の石をフリックし、現在の番号へ当てます。','5番到達または手数切れで終了。単独トップが勝ち、同点なら引き分けです。'],coopWin:'共有の制限手数内に5番までつなげれば、全員の勝ち。',tip:'先の番号に当てても進みません。現在の番号を確認しましょう。'}
  }},
  'zh-CN':{name:'简体中文',ui:{button:'? 30秒指南',eyebrow:'30秒指南',close:'关闭指南',done:'知道了',inGame:'当前玩法指南',tip:'小技巧'},labels:['目标','操作','获胜'],modeNames:{classic:'经典弹石',football:'足球',line:'贴线挑战',golf:'石子高尔夫',coop:'鬼怪讨伐',royal:'王座战',chain:'连锁目标'},modes:{
    classic:{steps:['把对方的棋子全部弹出棋盘。','按住自己的棋子，向发射方向的反方向拖动后松手。','自己的棋子仍在场、对方棋子全部出局即可获胜。'],tip:'擦着侧面撞击，往往能用更小的力把棋子推出去。'},
    football:{steps:['用自己的棋子击球，把球送进对方球门。','弹出棋子推动球，也可利用墙面反弹调整角度。','率先达到设定分数即可获胜。'],tip:'别只顾着大力击球，也要让棋子停在方便下一次进攻的位置。'},
    line:{steps:['不要越线，让棋子尽量停在线边。','每位玩家用自己的棋子弹射一次。','未越线的有效棋子中，离线最近的棋子获胜。'],tip:'先轻一点，摸清摩擦力会让棋子滑多远。'},
    golf:{steps:['把棋子打进洞，完成全部3个球洞。','避开岩石、长草区和墙壁，每回合击打一次。','3洞总杆数最少的玩家获胜。'],tip:'如果直攻会让下一杆更难，不妨选择更宽、更稳的路线。'},
    coop:{steps:['与队友合作，清除所有黑色鬼怪棋子。','轮流弹出自己的棋子，把鬼怪推出棋盘。','在次数或己方棋子耗尽前清完3波，所有人共同获胜。'],tip:'最大的鬼怪很重，要用多枚棋子连续推它。'},
    royal:{steps:['棋盘每轮都会缩小，坚持到最后。','保护自己的棋子，同时把对手推向危险的边缘。','棋盘上只剩己方棋子时获胜。'],tip:'尽量占据中央，棋盘缩小时会安全得多。'},
    chain:{steps:['按数字顺序击中1号到5号目标。','弹出自己的棋子，撞击当前号码的目标。','击中5号或次数用尽时结束；单独最高分者获胜，同分则平局。'],coopWin:'在共享的次数限制内完成到5号，所有人共同获胜。',tip:'提前击中后面的号码不会推进进度，出手前先确认当前目标。'}
  }}
};
