window.TTAK_GUIDE_LOCALES={
  es:{name:'Español',ui:{button:'? Guía en 30 s',eyebrow:'GUÍA EN 30 S',close:'Cerrar guía',done:'Entendido',inGame:'Guía del juego actual',tip:'Consejo rápido'},labels:['OBJETIVO','TU JUGADA','VICTORIA'],modeNames:{classic:'Clásico',football:'Fútbol',line:'Cerca de la línea',golf:'Golf de piedras',coop:'Caza de dokkaebi',royal:'Batalla real',chain:'Tiro con truco 1→5'},modes:{
    classic:{steps:['Expulsa del tablero todas las fichas rivales.','Mantén pulsada tu ficha, tira hacia atrás en sentido opuesto al disparo y suelta.','Ganas si quedan fichas tuyas y no queda ninguna rival.'],tip:'Un golpe lateral de refilón suele expulsar una ficha con menos fuerza.'},
    football:{steps:['Mete el balón en la portería rival usando tus fichas.','Elige 3 o 5 fichas por equipo; con 5, el campo se hace más grande.','Gana quien alcance primero la puntuación fijada.'],tip:'No te limites a golpear fuerte: deja fichas bien colocadas para la siguiente jugada.'},
    line:{steps:['Deja tu ficha lo más cerca posible de la línea sin cruzarla.','Cada jugador lanza una vez su propia ficha.','Gana quien deje la ficha válida más cercana a la línea.'],tip:'Empieza con suavidad y calcula cuánto frenará la fricción.'},
    golf:{steps:['Emboca tu ficha y completa los tres hoyos.','Da un golpe por turno y evita rocas y zonas que frenan la ficha.','Gana quien complete los tres hoyos con menos golpes.'],tip:'Busca una ruta amplia y segura si el tiro directo complica el siguiente golpe.'},
    coop:{steps:['Colaboren para eliminar todas las piedras negras de los duendes.','Los duendes contraatacan tras 5 turnos en fácil, 4 en normal y 3 en difícil.','Eliminen las tres oleadas antes de agotar las jugadas o perder todas sus fichas.'],tip:'El contador superior indica cuántos turnos faltan para el siguiente contraataque.'},
    royal:{steps:['Sobrevive hasta el final en un tablero que se reduce cada ronda.','Protege tus fichas y empuja a tus rivales hacia el borde peligroso.','Ganas cuando solo quedan fichas de tu equipo en el tablero.'],tip:'Controlar el centro te mantiene a salvo cuando el borde se cierra.'},
    chain:{steps:['Golpea 1→2→3→4→5 en orden con un solo tiro.','Usa las piedras y paredes de alto rebote para crear una carambola.','El primero que complete los cinco gana; si nadie lo logra tras varios turnos, los objetivos cambian de lugar.'],tip:'El ángulo del golpe al 1 decide la cadena hacia 2·3·4·5.'}
  }},
  'pt-BR':{name:'Português (Brasil)',ui:{button:'? Guia em 30 s',eyebrow:'GUIA EM 30 S',close:'Fechar guia',done:'Entendi',inGame:'Guia do jogo atual',tip:'Dica rápida'},labels:['OBJETIVO','SUA JOGADA','VITÓRIA'],modeNames:{classic:'Clássico',football:'Futebol',line:'Mais perto da linha',golf:'Golfe de pedras',coop:'Caça aos dokkaebi',royal:'Batalha real',chain:'Trick shot 1→5'},modes:{
    classic:{steps:['Tire do tabuleiro todas as pedras adversárias.','Pressione sua pedra, puxe no sentido oposto ao lançamento e solte.','Você vence se restarem pedras suas e nenhuma adversária.'],tip:'Uma batida lateral de raspão costuma expulsar a pedra com menos força.'},
    football:{steps:['Faça a bola entrar no gol adversário usando suas pedras.','Escolha 3 ou 5 pedras por equipe; com 5, o campo fica maior.','Vence quem alcançar primeiro a pontuação definida.'],tip:'Não bata só com força: deixe suas pedras bem posicionadas para a próxima jogada.'},
    line:{steps:['Pare sua pedra o mais perto possível da linha, sem ultrapassá-la.','Cada jogador lança a própria pedra uma vez.','Vence quem deixar a pedra válida mais próxima da linha.'],tip:'Comece devagar e calcule quanto a fricção vai frear a pedra.'},
    golf:{steps:['Coloque sua pedra no buraco e complete os três percursos.','Dê uma tacada por turno e evite pedras e áreas que reduzem a velocidade.','Vence quem completar os três buracos com menos tacadas.'],tip:'Escolha uma rota ampla e segura se o caminho direto dificultar a próxima tacada.'},
    coop:{steps:['Trabalhem juntos para eliminar todas as pedras pretas dos goblins.','Os goblins contra-atacam após 5 turnos no fácil, 4 no normal e 3 no difícil.','Eliminem as três ondas antes de acabarem as jogadas ou todas as pedras da equipe.'],tip:'O contador mostra quantos turnos faltam para o próximo contra-ataque.'},
    royal:{steps:['Sobreviva até o fim em um tabuleiro que encolhe a cada rodada.','Proteja suas pedras e empurre os rivais para a borda perigosa.','Você vence quando só restam pedras da sua equipe no tabuleiro.'],tip:'Dominar o centro mantém você mais seguro quando a borda se fecha.'},
    chain:{steps:['Acerte 1→2→3→4→5 em ordem com uma única tacada.','Use as pedras e paredes mais elásticas para criar uma carambola.','O primeiro a completar os cinco vence; sem vencedor por vários turnos, os alvos mudam de lugar.'],tip:'O ângulo no alvo 1 decide a sequência para 2·3·4·5.'}
  }},
  de:{name:'Deutsch',ui:{button:'? 30-Sekunden-Anleitung',eyebrow:'IN 30 SEKUNDEN ERKLÄRT',close:'Anleitung schließen',done:'Verstanden',inGame:'Anleitung zum aktuellen Spiel',tip:'Kurztipp'},labels:['ZIEL','DEIN ZUG','SIEG'],modeNames:{classic:'Klassisch',football:'Fußball',line:'Nah an die Linie',golf:'Steingolf',coop:'Dokkaebi-Jagd',royal:'Königskampf',chain:'Trickshot 1→5'},modes:{
    classic:{steps:['Stoße alle gegnerischen Steine vom Brett.','Drücke deinen Stein, ziehe entgegen der Schussrichtung und lass los.','Du gewinnst, wenn nur noch Steine deines Teams auf dem Brett liegen.'],tip:'Ein seitlicher Streifschuss befördert Steine oft mit weniger Kraft hinaus.'},
    football:{steps:['Spiele den Ball mit deinen Steinen ins gegnerische Tor.','Wähle 3 oder 5 Steine pro Team; bei 5 wird das Spielfeld größer.','Wer zuerst die gewählte Zielpunktzahl erreicht, gewinnt.'],tip:'Schlage nicht nur fest: Lass deine Steine auch günstig für den nächsten Zug liegen.'},
    line:{steps:['Bring deinen Stein so nah wie möglich an die Linie, ohne sie zu überqueren.','Jeder spielt genau einen Schuss mit dem eigenen Stein.','Der gültige Stein mit dem kleinsten Abstand gewinnt; Gleichstand ist remis.'],tip:'Beginne sanft und schätze ab, wie weit der Stein durch die Reibung noch gleitet.'},
    golf:{steps:['Spiele deinen Stein ins Loch und absolviere alle drei Bahnen.','Pro Zug spielst du einmal; meide Felsen und rauen Boden.','Nach drei Löchern gewinnt, wer insgesamt die wenigsten Schläge hat.'],tip:'Wähle lieber einen breiten, sicheren Weg, wenn der direkte Schuss den nächsten erschwert.'},
    coop:{steps:['Vertreibt gemeinsam alle schwarzen Goblin-Steine.','Die Goblins kontern nach 5 Zügen auf Leicht, 4 auf Normal und 3 auf Schwer.','Räumt alle drei Wellen, bevor euch Schüsse oder eigene Steine ausgehen.'],tip:'Der Zähler zeigt die Züge bis zum nächsten Gegenangriff.'},
    royal:{steps:['Bleib bis zuletzt auf dem Brett, das jede Runde kleiner wird.','Schütze deine Steine und dränge Gegner an den gefährlichen Rand.','Du gewinnst, wenn nur noch Steine deines Teams auf dem Brett liegen.'],tip:'Halte die Mitte: Dort bist du sicherer, wenn der Rand näher rückt.'},
    chain:{steps:['Triff 1→2→3→4→5 mit einem einzigen Schuss in dieser Reihenfolge.','Nutze besonders starke Abpraller von Steinen und Wänden für den Trickshot.','Wer alle fünf zuerst schafft, gewinnt; ohne Sieger werden die Ziele nach einigen Zügen neu verteilt.'],tip:'Der Winkel an Ziel 1 bestimmt die Kette zu 2·3·4·5.'}
  }},
  fr:{name:'Français',ui:{button:'? Guide en 30 s',eyebrow:'GUIDE EN 30 S',close:'Fermer le guide',done:'Compris',inGame:'Guide du jeu en cours',tip:'Astuce'},labels:['OBJECTIF','VOTRE COUP','VICTOIRE'],modeNames:{classic:'Classique',football:'Football',line:'Au plus près de la ligne',golf:'Golf de pierres',coop:'Chasse aux dokkaebi',royal:'Bataille royale',chain:'Tir acrobatique 1→5'},modes:{
    classic:{steps:['Éjectez du plateau toutes les pierres adverses.','Appuyez sur votre pierre, tirez dans le sens opposé au lancer, puis relâchez.','Vous gagnez s’il reste vos pierres et aucune pierre adverse.'],tip:'Un coup latéral en biais éjecte souvent une pierre avec moins de force.'},
    football:{steps:['Envoyez le ballon dans le but adverse avec vos pierres.','Choisissez 3 ou 5 pierres par équipe ; avec 5, le terrain s’agrandit.','Le premier à atteindre le score choisi gagne.'],tip:'Ne frappez pas seulement fort : placez aussi vos pierres pour le coup suivant.'},
    line:{steps:['Arrêtez votre pierre au plus près de la ligne sans la franchir.','Chaque joueur lance une fois sa propre pierre.','La pierre valide la plus proche de la ligne remporte la partie.'],tip:'Commencez doucement et estimez la distance de freinage.'},
    golf:{steps:['Mettez votre pierre dans le trou et terminez les trois parcours.','Jouez un coup par tour en évitant rochers et zones qui ralentissent la pierre.','Le joueur avec le moins de coups après trois trous gagne.'],tip:'Prenez une voie large et sûre si le tir direct complique le coup suivant.'},
    coop:{steps:['Coopérez pour éliminer toutes les pierres noires des gobelins.','Les gobelins ripostent après 5 tours en facile, 4 en normal et 3 en difficile.','Éliminez les trois vagues avant d’épuiser les coups ou toutes vos pierres.'],tip:'Le compteur indique les tours avant la prochaine riposte.'},
    royal:{steps:['Survivez jusqu’au bout sur un plateau qui rétrécit à chaque manche.','Protégez vos pierres et poussez vos rivaux vers le bord dangereux.','Vous gagnez quand seules les pierres de votre équipe restent sur le plateau.'],tip:'Contrôler le centre vous protège quand les limites se resserrent.'},
    chain:{steps:['Touchez 1→2→3→4→5 dans l’ordre en un seul tir.','Profitez des rebonds renforcés des pierres et des murs pour réussir la figure.','Le premier à réussir les cinq gagne ; sans vainqueur après plusieurs tours, les cibles changent de place.'],tip:'L’angle sur la cible 1 décide de la chaîne vers 2·3·4·5.'}
  }},
  ru:{name:'Русский',ui:{button:'? Правила за 30 секунд',eyebrow:'ПРАВИЛА ЗА 30 СЕКУНД',close:'Закрыть правила',done:'Понятно',inGame:'Правила текущей игры',tip:'Совет'},labels:['ЦЕЛЬ','ХОД','ПОБЕДА'],modeNames:{classic:'Классика',football:'Футбол',line:'Ближе к линии',golf:'Каменный гольф',coop:'Охота на токкэби',royal:'Королевская битва',chain:'Трик-шот 1→5'},modes:{
    classic:{steps:['Выбейте все камни соперников с поля.','Нажмите свой камень, оттяните против направления удара и отпустите.','Вы победите, если на поле останутся только камни вашей команды.'],tip:'Касательный удар сбоку часто выбивает камень с меньшей силой.'},
    football:{steps:['Забейте мяч камнями в ворота соперника.','Выберите 3 или 5 камней на команду; при 5 поле становится больше.','Побеждает тот, кто первым наберёт выбранное число очков.'],tip:'Не бейте только на силу: оставляйте камни в удобных позициях для следующего хода.'},
    line:{steps:['Остановите камень как можно ближе к линии, не пересекая её.','Каждый игрок делает ровно один бросок своим камнем.','Ближайший камень, не пересёкший линию, побеждает; при равенстве — ничья.'],tip:'Начните с лёгкого удара и оцените, как трение замедляет камень.'},
    golf:{steps:['Загоните камень в лунку и пройдите все три лунки.','Делайте по одному удару за ход, обходя камни и участки высокой травы.','После трёх лунок побеждает игрок с наименьшим общим числом ударов.'],tip:'Выбирайте широкий безопасный путь, если прямой удар усложнит следующий.'},
    coop:{steps:['Вместе выбейте все чёрные камни-гоблины.','Гоблины отвечают через 5 ходов на лёгком, 4 на среднем и 3 на сложном уровне.','Очистите три волны, пока не кончились общие броски или ваши камни.'],tip:'Счётчик показывает ходы до следующей контратаки.'},
    royal:{steps:['Продержитесь до конца на поле, которое сужается каждый раунд.','Берегите свои камни и выталкивайте соперников к опасному краю.','Вы победите, если на поле останутся только камни вашей команды.'],tip:'Держитесь центра: там безопаснее, когда границы сдвигаются.'},
    chain:{steps:['Одним броском поразите 1→2→3→4→5 строго по порядку.','Используйте усиленные отскоки камней и стен для трюкового удара.','Первый выполнивший всю пятёрку побеждает; без победителя цели меняют места через несколько ходов.'],tip:'Угол удара по цели 1 задаёт цепочку 2·3·4·5.'}
  }},
  ja:{name:'日本語',ui:{button:'? 30秒ガイド',eyebrow:'30秒ガイド',close:'ガイドを閉じる',done:'わかった',inGame:'このゲームのガイド',tip:'ワンポイント'},labels:['目的','操作','勝利'],modeNames:{classic:'ベーシック',football:'サッカー',line:'ラインぎりぎり',golf:'ストーンゴルフ',coop:'トッケビ退治',royal:'王座戦',chain:'トリックショット1→5'},modes:{
    classic:{steps:['相手の石をすべて盤外へ弾き出そう。','自分の石をタッチし、飛ばす方向と逆へ引いて離します。','自分の石が残り、相手の石がすべてなくなれば勝ち。'],tip:'正面より側面をかすめるように当てると、弱い力でも押し出しやすくなります。'},
    football:{steps:['自分の石でボールを弾き、相手ゴールに入れよう。','チームごとに石を3個か5個から選べます。5個ならコートも広くなります。','設定した目標点に先に到達すれば勝ち。'],tip:'強く当てるだけでなく、次に使いやすい位置へ石を残しましょう。'},
    line:{steps:['ラインを越えず、できるだけ近くに石を止めよう。','各プレイヤーが自分の石を1回ずつ飛ばします。','ライン手前の有効な石のうち、最も近い石が勝ち。'],tip:'最初は弱めに飛ばし、摩擦で止まる距離をつかみましょう。'},
    golf:{steps:['石をカップに入れ、全3ホールを回ろう。','岩やラフ、壁を避けながら、各ターンに1打します。','3ホールの合計打数が最も少ないプレイヤーが勝ち。'],tip:'直線狙いで次が難しくなるなら、広く安全なルートを選びましょう。'},
    coop:{steps:['仲間と協力し、黒い鬼の石をすべて退治しよう。','鬼は難易度が易しいなら5手、普通なら4手、難しいなら3手後に反撃します。','手数か味方の石が尽きる前に全3ウェーブをクリアすれば、全員の勝ち。'],tip:'上のカウンターで次の反撃までの手数を確認しましょう。'},
    royal:{steps:['ラウンドごとに縮む盤で、最後まで生き残ろう。','自分の石を守りながら、相手を危険な端へ押し出します。','盤上に自分のチームの石だけが残れば勝ち。'],tip:'中央を取ると、盤が縮んでも生き残りやすくなります。'},
    chain:{steps:['1回のショットで1→2→3→4→5を順番にすべて当てよう。','反発の強い石と壁を使って連続トリックショットを作ります。','最初に5個すべて成功した人の勝ち。数ターン決まらなければターゲットが再配置されます。'],tip:'1番へ当てる角度が2·3·4·5への連鎖を決めます。'}
  }},
  'zh-CN':{name:'简体中文',ui:{button:'? 30秒指南',eyebrow:'30秒指南',close:'关闭指南',done:'知道了',inGame:'当前玩法指南',tip:'小技巧'},labels:['目标','操作','获胜'],modeNames:{classic:'经典弹石',football:'足球',line:'贴线挑战',golf:'石子高尔夫',coop:'鬼怪讨伐',royal:'王座战',chain:'花式连击1→5'},modes:{
    classic:{steps:['把对方的棋子全部弹出棋盘。','按住自己的棋子，向发射方向的反方向拖动后松手。','自己的棋子仍在场、对方棋子全部出局即可获胜。'],tip:'擦着侧面撞击，往往能用更小的力把棋子推出去。'},
    football:{steps:['用自己的棋子击球，把球送进对方球门。','每队可选3枚或5枚棋子；选择5枚时球场会扩大。','率先达到设定分数即可获胜。'],tip:'别只顾着大力击球，也要让棋子停在方便下一次进攻的位置。'},
    line:{steps:['不要越线，让棋子尽量停在线边。','每位玩家用自己的棋子弹射一次。','未越线的有效棋子中，离线最近的棋子获胜。'],tip:'先轻一点，摸清摩擦力会让棋子滑多远。'},
    golf:{steps:['把棋子打进洞，完成全部3个球洞。','避开岩石、长草区和墙壁，每回合击打一次。','3洞总杆数最少的玩家获胜。'],tip:'如果直攻会让下一杆更难，不妨选择更宽、更稳的路线。'},
    coop:{steps:['与队友合作，清除所有黑色鬼怪棋子。','鬼怪会在简单5回合、普通4回合、困难3回合后反击。','在次数或己方棋子耗尽前清完3波，所有人共同获胜。'],tip:'顶部计数器会显示距离下一次反击还有几回合。'},
    royal:{steps:['棋盘每轮都会缩小，坚持到最后。','保护自己的棋子，同时把对手推向危险的边缘。','棋盘上只剩己方棋子时获胜。'],tip:'尽量占据中央，棋盘缩小时会安全得多。'},
    chain:{steps:['用一次击球按顺序击中1→2→3→4→5。','利用更强的棋子与墙面反弹完成连续花式击球。','最先完成五个目标者获胜；若数回合无人成功，目标会重新随机布置。'],tip:'击中1号的角度会决定后续2·3·4·5的连锁路线。'}
  }}
};
