/* global TtakPhysics,TtakRules,TtakAI,io */
'use strict';
const P=TtakPhysics,R=TtakRules,AI=TtakAI,$=s=>document.querySelector(s);
const names={classic:['기본 알까기','CLASSIC'],football:['골까기','FOOTBALL'],line:['금 가까이','LINE'],golf:['홀인돌','GOLF'],coop:['도깨비 소탕','CO-OP'],royal:['왕좌전','ROYAL'],chain:['연쇄 표적','CHAIN']};
const colors=['#a34735','#31485f','#496150','#b98b45'];
let flow='single',game=null,selected=null,aim=null,particles=[],muted=false,paused=false,last=performance.now(),acc=0,aiPending=false,counterPending=false,shotSeq=0,socket=null,online=false,roomCode='',myId='',audio=null,lifecycleEpoch=0;
for(const [id,[ko,en]] of Object.entries(names)){const b=document.createElement('button');b.className=`mode-mark pigment-${Object.keys(names).indexOf(id)%4}`;b.dataset.mode=id;b.innerHTML=`<i></i><b>${ko}</b><small>${en}</small>`;$('#modeList').append(b);const o=new Option(`${ko} · ${en}`,id);$('#mode').add(o);}
function show(id){for(const el of ['home','setup','game'])$('#'+el).classList.toggle('hidden',id!==el);if(id==='game')$('#game').focus();}
function syncFormation(){const classic=$('#mode').value==='classic';$('#formationWrap').classList.toggle('hidden',!classic);$('#formation').disabled=!classic;}
function configure(f){flow=f;show('setup');$('#difficultyWrap').classList.toggle('hidden',f!=='single');$('#onlineBox').classList.toggle('hidden',f!=='online');$('.inkbtn').classList.toggle('hidden',f==='online');$('#players').value='2';$('#setupTitle').textContent=f==='online'?'온라인 방 / ONLINE ROOM':f==='local'?'마주 놀기 / LOCAL':'혼자 놀기 / SINGLE';syncFormation();}
document.querySelectorAll('[data-flow]').forEach(b=>b.onclick=()=>configure(b.dataset.flow));document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show('home'));document.querySelectorAll('.mode-mark').forEach(b=>b.onclick=()=>{$('#mode').value=b.dataset.mode;configure('single')});
$('#mode').onchange=syncFormation;
function settings(){const n=+$('#amount').value||5,mode=$('#mode').value;return mode==='classic'?{discs:n,formation:$('#formation').value||'standard'}:mode==='football'?{targetScore:Math.min(9,n)}:mode==='line'?{throws:Math.min(9,n)}:mode==='royal'?{discs:Math.min(8,n)}:mode==='chain'?{turnLimit:Math.max(5,n*3),coop:$('#coopRule').checked}:{}};
$('#setupForm').onsubmit=e=>{e.preventDefault();const m=$('#mode').value;startLocal(m,flow==='single'&&m==='golf'?2:+$('#players').value)};
function resetLifecycle(){lifecycleEpoch++;selected=aim=null;paused=false;aiPending=counterPending=false;acc=0;$('#pause').textContent='멈춤';$('#thinking').classList.add('hidden');}
function startLocal(mode,players){online=false;game=R.createGame({mode,players,settings:settings()});game.ai=flow==='single'&&game.players>1;game.difficulty=$('#difficulty').value;enterGame();}
function enterGame(){resetLifecycle();show('game');$('#modeTitle').textContent=names[game.mode].join(' · ');$('#copyCode').classList.toggle('hidden',!online);resize();announce();}
function announce(msg){if(!game)return;const who=game.mode==='coop'?`${game.turn+1}번`:game.mode==='golf'&&game.ai&&game.turn===1?'2번(AI)':`${game.turn+1}번`;$('#status').textContent=msg||(game.phase==='finished'?(game.winner==null?'판이 끝났습니다':`${game.winner+1}번 승리!`):game.phase==='counter'?'도깨비가 반격을 노립니다…':game.phase==='simulating'?'돌이 구르는 중…':`${who} 차례 · 돌을 당겨 놓으세요`);$('#score').textContent=game.mode==='coop'?`물결 ${game.wave||1} · 기회 ${game.turnBudget}`:game.mode==='golf'?`홀 ${(game.hole||0)+1}/3 · ${game.scores.join(' : ')}`:game.scores?.some(Boolean)?game.scores.join(' : '):`제 ${game.round||1}판`;}
const canvas=$('#board'),ctx=canvas.getContext('2d');
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.width*.6*d);ctx.setTransform(canvas.width/1200,0,0,canvas.height/720,0,0);}
addEventListener('resize',resize);
function pointer(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*1200/r.width,y:(e.clientY-r.top)*720/r.height};}
canvas.onpointerdown=e=>{if(!game||online&&game.phase!=='aiming'||paused)return;ensureAudio();const p=pointer(e),legal=R.eligibleObjects(game);const o=legal.find(d=>Math.hypot(d.x-p.x,d.y-p.y)<=d.radius+14);if(!o)return invalid('내 차례의 돌을 골라주세요');selected=o;aim=p;canvas.setPointerCapture(e.pointerId)};
canvas.onpointermove=e=>{if(aim)aim=pointer(e)};
canvas.onpointercancel=()=>{selected=aim=null;};
canvas.onpointerup=e=>{if(!selected||!aim)return;const force={x:(selected.x-aim.x)*7.2,y:(selected.y-aim.y)*7.2},mag=Math.hypot(force.x,force.y);if(mag<80){selected=aim=null;return invalid('조금 더 당겨주세요');}if(mag>P.MAX_SPEED){force.x*=P.MAX_SPEED/mag;force.y*=P.MAX_SPEED/mag;}fire(selected.id,force);selected=aim=null;};
function fire(id,force){clack(.12,0);if(online){socket.emit('game:shot',{id,force,seq:++shotSeq},r=>{if(!r?.ok)invalid(r?.error||'쏠 수 없습니다')});return;}if(!R.markShot(game,id))return invalid('지금은 쏠 수 없습니다');P.applyShot(game.objects.find(o=>o.id===id),force);announce();}
function invalid(msg){announce(msg);canvas.classList.add('impact');setTimeout(()=>canvas.classList.remove('impact'),180);clack(.04,-400);}
function simulation(dt){if(!game||online||paused||game.phase!=='simulating')return;acc+=Math.min(dt,.05);let events=[];while(acc>=1/120){events.push(...P.step(game.objects,1/120,game.board));acc-=1/120;}P.accumulateEvents(game.pendingEvents||(game.pendingEvents=[]),events);for(const e of events)if(e.type==='impact'){burst(e.x,e.y,e.strength);clack(Math.min(.18,e.strength/2000),(e.x/1200-.5)*500)}if(P.allResting(game.objects)){R.resolve(game,P.consumeEvents(game));announce();if(game.phase==='counter')scheduleGoblinCounter();else if(game.ai&&game.phase==='aiming'&&game.turn>0){const lifecycleToken=lifecycleEpoch;setTimeout(()=>{if(lifecycleToken===lifecycleEpoch)aiTurn()},450);}}}
function scheduleGoblinCounter(){if(counterPending||!game||game.phase!=='counter')return;const lifecycleToken=lifecycleEpoch;counterPending=true;announce('도깨비가 반격을 노립니다…');setTimeout(()=>{if(lifecycleToken!==lifecycleEpoch)return;counterPending=false;if(!game||game.phase!=='counter')return;const s=AI.chooseGoblinShot(game,game.shot*4099+game.wave);if(s&&R.beginGoblinCounter(game,s.id)){const attacker=game.objects.find(o=>o.id===s.id);P.applyShot(attacker,s.force);burst(attacker.x,attacker.y,240);announce();}},500);}
function aiTurn(){if(!game||game.phase!=='aiming'||game.turn===0)return;const lifecycleToken=lifecycleEpoch;aiPending=true;$('#thinking').classList.remove('hidden');requestAnimationFrame(()=>setTimeout(()=>{if(lifecycleToken!==lifecycleEpoch)return;const s=AI.chooseShot(game,game.difficulty);aiPending=false;$('#thinking').classList.add('hidden');if(s)fire(s.id,s.force)},250));}
function burst(x,y,power){for(let i=0;i<Math.min(10,2+power/100);i++)particles.push({x,y,vx:(Math.random()-.5)*power*.3,vy:(Math.random()-.5)*power*.3,life:1});}
function paper(){ctx.fillStyle='#e7dcc1';ctx.fillRect(0,0,1200,720);ctx.globalAlpha=.1;for(let i=0;i<90;i++){ctx.strokeStyle=i%3?'#594a37':'#9a4735';ctx.beginPath();const y=(i*83)%720;ctx.moveTo((i*137)%1200,y);ctx.quadraticCurveTo(600,y+(i%5-2)*4,1200,y+2);ctx.stroke()}ctx.globalAlpha=1;ctx.strokeStyle='#24211d55';ctx.lineWidth=3;ctx.setLineDash([14,9]);ctx.strokeRect(34,34,1132,652);ctx.setLineDash([]);}
function motif(){ctx.save();ctx.strokeStyle='#31485f55';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(55,620);ctx.bezierCurveTo(100,575,130,650,170,602);ctx.bezierCurveTo(205,566,235,630,270,600);ctx.stroke();ctx.translate(1070,82);ctx.beginPath();ctx.ellipse(0,0,45,23,-.2,0,7);ctx.moveTo(-38,3);ctx.quadraticCurveTo(-70,18,-82,4);ctx.moveTo(33,-7);ctx.lineTo(58,-25);ctx.stroke();ctx.restore();}
function modeArt(){const b=game.board;ctx.save();if(game.mode==='classic'){const q=b.geometry.grid,f=b.geometry.frame;ctx.fillStyle='#c79a58';ctx.fillRect(0,0,1200,720);ctx.strokeStyle='#7a4d27';ctx.globalAlpha=.22;ctx.lineWidth=2;for(let i=0;i<34;i++){const y=18+i*21;ctx.beginPath();ctx.moveTo(18,y);ctx.bezierCurveTo(270,y+(i%5-2)*5,760,y+(i%7-3)*4,1182,y+(i%4-2)*3);ctx.stroke();}ctx.globalAlpha=1;ctx.strokeStyle='#5b351d';ctx.lineWidth=18;ctx.strokeRect(f.x,f.y,f.w,f.h);ctx.strokeStyle='#262019';ctx.lineWidth=2;for(let i=0;i<q.lines;i++){const p=i*q.spacing;ctx.beginPath();ctx.moveTo(q.left+p,q.top);ctx.lineTo(q.left+p,q.top+q.spacing*18);ctx.moveTo(q.left,q.top+p);ctx.lineTo(q.left+q.spacing*18,q.top+p);ctx.stroke();}ctx.fillStyle='#262019';for(const star of b.geometry.stars){ctx.beginPath();ctx.arc(q.left+star.column*q.spacing,q.top+star.row*q.spacing,5,0,7);ctx.fill();}}
if(game.mode==='football'){const f=b.geometry;ctx.fillStyle='#27362e';ctx.fillRect(0,0,1200,720);ctx.fillStyle='#496846';ctx.fillRect(f.touchline.x,f.touchline.y,f.touchline.w,f.touchline.h);const stripeW=f.touchline.w/10;for(let i=0;i<10;i++){ctx.fillStyle=i%2?'#52744d':'#466743';ctx.fillRect(f.touchline.x+i*stripeW,f.touchline.y,stripeW,f.touchline.h);}ctx.globalAlpha=.13;ctx.strokeStyle='#d8d0ad';ctx.lineWidth=2;for(let i=0;i<18;i++){const x=f.touchline.x+(i*97)%f.touchline.w;ctx.beginPath();ctx.moveTo(x,f.touchline.y);ctx.lineTo(Math.min(f.touchline.x+f.touchline.w,x+34),f.touchline.y+f.touchline.h);ctx.stroke();}ctx.globalAlpha=1;ctx.strokeStyle='#eee8d1';ctx.lineWidth=6;ctx.strokeRect(f.touchline.x,f.touchline.y,f.touchline.w,f.touchline.h);ctx.beginPath();ctx.moveTo(f.touchline.x,f.halfway.y);ctx.lineTo(f.touchline.x+f.touchline.w,f.halfway.y);ctx.arc(f.center.x,f.center.y,f.center.radius,0,7);ctx.stroke();ctx.fillStyle='#eee8d1';ctx.beginPath();ctx.arc(f.center.x,f.center.y,6,0,7);ctx.fill();for(const box of f.penaltyBoxes)ctx.strokeRect(box.x,box.y,box.w,box.h);const goalDepth=18,top=f.touchline.y,bottom=f.touchline.y+f.touchline.h;ctx.lineWidth=4;ctx.strokeRect(f.goals.x1,top-goalDepth,f.goals.x2-f.goals.x1,goalDepth);ctx.strokeRect(f.goals.x1,bottom,f.goals.x2-f.goals.x1,goalDepth);for(let x=f.goals.x1+20;x<f.goals.x2;x+=20){ctx.beginPath();ctx.moveTo(x,top-goalDepth);ctx.lineTo(x,top);ctx.moveTo(x,bottom);ctx.lineTo(x,bottom+goalDepth);ctx.stroke();}}
if(game.mode==='line'){ctx.strokeStyle='#a34735';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(65,b.targetLine);ctx.lineTo(1135,b.targetLine);ctx.stroke();for(let x=80;x<1150;x+=42){ctx.beginPath();ctx.moveTo(x,50);ctx.lineTo(x,670);ctx.strokeStyle='#49615033';ctx.stroke();}}
if(game.mode==='golf'){ctx.fillStyle='#3f5e3f';ctx.fillRect(0,0,1200,720);ctx.fillStyle='#79915b';ctx.beginPath();(b.fairway||[]).forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fill();ctx.strokeStyle='#314b35';ctx.lineWidth=3;ctx.stroke();for(const z of b.rough||[]){ctx.fillStyle='#304d37';ctx.fillRect(z.x,z.y,z.w,z.h);ctx.strokeStyle='#91a26a55';ctx.lineWidth=2;for(let x=z.x;x<z.x+z.w;x+=18){ctx.beginPath();ctx.moveTo(x,z.y+z.h);ctx.lineTo(x+9,z.y);ctx.stroke();}}const green=b.puttingGreen;ctx.fillStyle='#9caf72';ctx.globalAlpha=.78;ctx.beginPath();ctx.ellipse(green.x,green.y,green.rx,green.ry,.04,0,7);ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle='#516b43';ctx.lineWidth=2;ctx.stroke();for(const z of b.bunkers||[]){ctx.fillStyle='#d2b875';ctx.beginPath();ctx.ellipse(z.x,z.y,z.rx,z.ry,-.12,0,7);ctx.fill();ctx.strokeStyle='#6f633f';ctx.stroke();}for(const r of b.rocks||[]){ctx.fillStyle='#655d50';ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,7);ctx.fill();ctx.strokeStyle='#29241f';ctx.stroke();}ctx.fillStyle='#24211d';ctx.beginPath();ctx.arc(b.cup.x,b.cup.y,b.cup.r,0,7);ctx.fill();ctx.strokeStyle='#a34735';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(b.cup.x,b.cup.y);ctx.lineTo(b.cup.x,b.cup.y-90);ctx.lineTo(b.cup.x+55,b.cup.y-70);ctx.lineTo(b.cup.x,b.cup.y-52);ctx.stroke();}if(game.mode==='royal'){ctx.strokeStyle='#a34735';ctx.lineWidth=10;ctx.strokeRect(b.inset,b.inset,1200-b.inset*2,720-b.inset*2);}ctx.restore();}
function drawDisc(o){if(o.kind==='rock')return;ctx.save();ctx.translate(o.x,o.y);const moving=Math.hypot(o.vx,o.vy)>20;if(moving)ctx.scale(1.06,.94);ctx.fillStyle=o.kind==='goblin'?'#24211d':o.kind==='ball'?'#eee8d1':o.kind==='target'?'#e7dcc1':colors[o.team%4]||'#24211d';ctx.strokeStyle='#24211d';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,o.radius,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.globalAlpha=.35;ctx.beginPath();ctx.arc(-3,2,o.radius-8,.2,5.7);ctx.strokeStyle='#e7dcc1';ctx.lineWidth=2;ctx.stroke();ctx.globalAlpha=1;ctx.fillStyle=o.kind==='goblin'?'#e7dcc1':'#24211d';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`900 ${o.radius*.9}px serif`;ctx.fillText(o.kind==='target'?o.number:o.kind==='goblin'?(o.heavy?'王':'鬼'):o.kind==='ball'?'●':(o.team??0)+1,0,2);if(o.kind==='goblin'){ctx.beginPath();ctx.moveTo(-16,-o.radius+5);ctx.lineTo(-8,-o.radius-12);ctx.lineTo(0,-o.radius+2);ctx.moveTo(7,-o.radius+3);ctx.lineTo(17,-o.radius-10);ctx.lineTo(19,-o.radius+8);ctx.stroke();}ctx.restore();}
function render(dt){if(game){paper();motif();modeArt();for(const o of game.objects)if(o.active)drawDisc(o);if(selected&&aim){const dx=selected.x-aim.x,dy=selected.y-aim.y,m=Math.min(210,Math.hypot(dx,dy));ctx.strokeStyle='#a34735';ctx.lineWidth=5;ctx.setLineDash([13,8]);ctx.beginPath();ctx.moveTo(selected.x,selected.y);ctx.lineTo(aim.x,aim.y);ctx.stroke();ctx.setLineDash([]);const a=Math.atan2(dy,dx);ctx.globalAlpha=.35;for(let i=1;i<6;i++){ctx.beginPath();ctx.arc(selected.x+Math.cos(a)*i*45,selected.y+Math.sin(a)*i*45,6-i*.6,0,7);ctx.fillStyle='#a34735';ctx.fill();}ctx.globalAlpha=1;for(let i=1;i<=5;i++){ctx.fillStyle=i*42<m?'#a34735':'#24211d44';ctx.fillRect(50+i*20,670,13,-i*7);}}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt*2;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle='#6d5540';ctx.fillRect(p.x,p.y,3,3)}ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0);}}
function frame(now){const dt=(now-last)/1000;last=now;simulation(dt);render(dt);requestAnimationFrame(frame)}requestAnimationFrame(frame);
function ensureAudio(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();}
function clack(gain=.1,pan=0){if(muted)return;ensureAudio();const o=audio.createOscillator(),g=audio.createGain(),f=audio.createBiquadFilter();o.type='triangle';o.frequency.setValueAtTime(260+pan*.1,audio.currentTime);o.frequency.exponentialRampToValueAtTime(70,audio.currentTime+.07);f.type='bandpass';f.frequency.value=850+pan;g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.1);o.connect(f).connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.11)}
$('#mute').onclick=()=>{muted=!muted;$('#mute').textContent=muted?'소리 끔 / MUTED':'소리 켬 / SOUND';$('#mute').setAttribute('aria-pressed',muted)};$('#pause').onclick=()=>{if(online)return invalid('온라인 판은 멈출 수 없습니다');paused=!paused;$('#pause').textContent=paused?'계속':'멈춤'};$('#leave').onclick=()=>{resetLifecycle();game=null;if(socket)socket.disconnect();socket=null;online=false;roomCode=myId='';shotSeq=0;show('home')};
$('#help').onclick=()=>$('#helpDialog').showModal();$('#helpDialog .close').onclick=()=>$('#helpDialog').close();
document.onkeydown=e=>{if(!game||game.phase!=='aiming'||online)return;const legal=R.eligibleObjects(game);if(!selected)selected=legal[0];if(!selected)return;if(!aim)aim={x:selected.x-100,y:selected.y};const key={ArrowLeft:[-12,0],ArrowRight:[12,0],ArrowUp:[0,-12],ArrowDown:[0,12]}[e.key];if(key){e.preventDefault();aim.x+=key[0];aim.y+=key[1]}if(e.code==='Space'){e.preventDefault();fire(selected.id,{x:(selected.x-aim.x)*7.2,y:(selected.y-aim.y)*7.2});selected=aim=null;}};
function connect(){if(socket)return;socket=io();socket.on('connect',()=>{$('#connection').textContent='● 연결됨';$('#connection').classList.add('on');const token=roomCode&&localStorage.getItem(`ttak:${roomCode}`);if(token)socket.emit('room:join',{name:$('#name').value,code:roomCode,token},r=>{if(r?.ok&&!r.spectator)myId=r.id})});socket.on('disconnect',()=>{$('#connection').textContent='● 재연결 중';$('#connection').classList.remove('on')});socket.on('room:state',room=>{roomCode=room.code;renderLobby(room)});socket.on('game:snapshot',snap=>{game=snap;online=true;if($('#game').classList.contains('hidden'))enterGame();announce()});socket.on('game:event',ev=>{for(const e of [].concat(ev)){if(e.type==='impact')burst(e.x,e.y,e.strength||100);if(e.type==='goblin-shot'){const attacker=game?.objects.find(o=>o.id===e.id);e.x??=attacker?.x;e.y??=attacker?.y;burst(e.x,e.y,e.strength||240);}}});socket.on('game:turn',()=>announce());}
$('#createRoom').onclick=()=>{connect();socket.emit('room:create',{name:$('#name').value,mode:$('#mode').value,settings:settings()},r=>{if(!r.ok)return invalidSetup(r.error);roomCode=r.code;myId=r.id;localStorage.setItem(`ttak:${r.code}`,r.token)})};
$('#joinRoom').onclick=()=>{connect();const c=$('#roomCode').value.toUpperCase();socket.emit('room:join',{name:$('#name').value,code:c,token:localStorage.getItem(`ttak:${c}`)},r=>{if(!r.ok)return invalidSetup(r.error);roomCode=c;myId=r.id;localStorage.setItem(`ttak:${c}`,r.token)})};
function invalidSetup(s){$('#lobby').textContent=s}
function renderLobby(r){const mine=r.players.find(p=>p.id===myId);$('#lobby').innerHTML=`<p><b>방 ${r.code}</b> · ${names[r.mode][0]}</p>${r.players.map(p=>`<span>${p.name} ${p.ready?'✓ 준비':'· 기다림'}${p.id===r.host?' [방장]':''}</span>`).join('<br>')}<div><button id="readyBtn">${mine?.ready?'준비 풀기':'준비'}</button>${r.host===myId?'<button id="startBtn">시작</button>':''}</div>`;$('#readyBtn').onclick=()=>socket.emit('room:ready',{ready:!mine?.ready});const st=$('#startBtn');if(st)st.onclick=()=>socket.emit('room:start',{},x=>{if(!x.ok)invalidSetup(x.error)});}
$('#copyCode').onclick=async()=>{await navigator.clipboard.writeText(roomCode);$('#copyCode').textContent=`${roomCode} 복사됨`};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
const safeState=()=>game?Object.freeze({mode:game.mode,formation:game.settings?.formation||null,orientation:game.board.orientation||null,phase:game.phase,turn:game.turn,objects:game.objects.filter(o=>o.active).length,connection:socket?.connected?'connected':'local'}):Object.freeze({mode:null,formation:null,orientation:null,phase:'lobby',turn:null,objects:0,connection:socket?.connected?'connected':'local'});
const selectMode=m=>{if(!R.MODES.includes(m))return false;$('#mode').value=m;syncFormation();return true};
window.__TTAK__=Object.freeze({state:safeState,selectMode,startSingle:(m='classic',d='normal')=>{flow='single';m=R.MODES.includes(m)?m:'classic';selectMode(m);$('#difficulty').value=d;startLocal(m,2);return safeState()},fireLegal:()=>{const o=game&&R.eligibleObjects(game)[0];if(!o)return false;fire(o.id,{x:650,y:0});return true},counts:()=>safeState()});
